import { describe, expect, it, vi } from 'vitest'
import { setupWebpackV5UnitTest, FakeConcatSource, createAssetsFromStore, createBundlerGeneratedCssMarker, path, testState, WeappTailwindcss } from './shared'
describe('bundlers/webpack WeappTailwindcss / generated css loader assets', () => {
  setupWebpackV5UnitTest()
  it('skips css assets already generated by the webpack loader pipeline', async () => {
    const processAssetsCallbacks: Array<(assets: Record<string, any>) => Promise<void>> = []
    let currentAssetStore: Record<string, string> = {}
    const updateAsset = vi.fn((file: string, source: FakeConcatSource) => {
      currentAssetStore[file] = source.toString()
    })
    const compilation = {
      compiler: { outputPath: path.resolve(process.cwd(), 'dist') },
      chunks: [{ id: 'main', hash: 'hash-1' }],
      hooks: {
        processAssets: {
          tapPromise: (_options: unknown, handler: (assets: Record<string, any>) => Promise<void>) => {
            processAssetsCallbacks.push(handler)
          },
        },
      },
      updateAsset,
      getAsset(file: string) {
        const content = currentAssetStore[file]
        if (content === undefined) {
          return undefined
        }
        return {
          source: {
            source: () => content,
          },
        }
      },
    }
    const compiler = {
      webpack: {
        Compilation: {
          PROCESS_ASSETS_STAGE_SUMMARIZE: Symbol('stage'),
        },
        sources: {
          ConcatSource: FakeConcatSource,
        },
        NormalModule: {
          getCompilationHooks: vi.fn(() => ({
            loader: {
              tap: vi.fn(),
            },
          })),
        },
      },
      hooks: {
        normalModuleFactory: {
          tap: vi.fn((_name: string, handler: (factory: any) => void) => {
            handler({
              hooks: {
                beforeResolve: {
                  tap: vi.fn(),
                },
              },
            })
          }),
        },
        compilation: {
          tap: vi.fn((_name: string, handler: (_compilation: any) => void) => {
            handler(compilation)
          }),
        },
      },
    }

    testState.currentContext.tailwindRuntime.majorVersion = 4
    const plugin = new WeappTailwindcss()
    plugin.apply(compiler as any)

    const generatedCss = [
      createBundlerGeneratedCssMarker('webpack', '/repo/src/app.css'),
      '.bg-clip-text{-webkit-background-clip:text;background-clip:text}',
    ].join('\n')
    currentAssetStore = {
      'app.css': generatedCss,
    }
    await processAssetsCallbacks[0](createAssetsFromStore(currentAssetStore))

    expect(testState.currentContext.styleHandler).not.toHaveBeenCalled()
    expect(updateAsset).toHaveBeenCalledWith('app.css', expect.any(FakeConcatSource))
    expect(updateAsset.mock.calls[0]?.[1].toString()).toBe('.bg-clip-text{-webkit-background-clip:text;background-clip:text}')
    expect(testState.currentContext.onUpdate).toHaveBeenCalledWith('app.css', generatedCss, '.bg-clip-text{-webkit-background-clip:text;background-clip:text}')
  })

})
