import { describe, expect, it, vi } from 'vitest'
import type { LoaderModule } from './shared'
import { setupWebpackV5UnitTest, FakeConcatSource, createAssetsFromStore, createBundlerGeneratedCssMarker, createContext, getWebpackLoaderRuntime, isCssImportRewriteLoader, path, replaceWxml, testState, WeappTailwindcss } from './shared'
describe('bundlers/webpack WeappTailwindcss / registered source css taro main', () => {
  setupWebpackV5UnitTest()
  it('does not regenerate taro main wxss after the source css entry was generated by webpack loaders', async () => {
    const generatedClass = replaceWxml('text-[40px]')
    testState.currentContext = createContext({
      rewriteCssImports: true,
      cssMatcher: (file: string) => file.endsWith('.wxss'),
      mainCssChunkMatcher: vi.fn((file: string) => file === 'app.wxss'),
      styleHandler: vi.fn(async (code: string) => ({ css: `handled:${code}` })),
      tailwindRuntime: {
        ...createContext().tailwindRuntime,
        getClassSet: vi.fn(async () => new Set(['text-[40px]'])),
        getClassSetSync: vi.fn(() => new Set(['text-[40px]'])),
        extract: vi.fn(async () => ({ classSet: new Set(['text-[40px]']) })),
        majorVersion: 4,
        options: {
          tailwindcss: {
            v4: {
              cssEntries: ['/workspace/src/app.css'],
            },
          },
        },
      } as any,
    })

    const processAssetsCallbacks: Array<(assets: Record<string, any>) => Promise<void>> = []
    let loaderHandler: ((loaderContext: any, module: LoaderModule) => void) | undefined
    let assetStore: Record<string, string> = {
      'app.wxss': [
        createBundlerGeneratedCssMarker('webpack', '/workspace/src/app.css'),
        `.${generatedClass}{font-size:40px}`,
      ].join('\n'),
    }
    const compilation = {
      compiler: { outputPath: path.resolve(process.cwd(), 'dist') },
      chunks: [{ id: 'app', hash: 'hash-generated', files: ['app.wxss'] }],
      hooks: {
        processAssets: {
          tapPromise: (_options: unknown, handler: (assets: Record<string, any>) => Promise<void>) => {
            processAssetsCallbacks.push(handler)
          },
        },
      },
      updateAsset: vi.fn((file: string, source: FakeConcatSource) => {
        assetStore[file] = source.toString()
      }),
      getAsset(file: string) {
        const content = assetStore[file]
        if (content === undefined) {
          return undefined
        }
        return {
          source: {
            source: () => content,
          },
        }
      },
    }
    const compiler = {
      webpack: {
        Compilation: {
          PROCESS_ASSETS_STAGE_SUMMARIZE: Symbol('stage'),
        },
        sources: {
          ConcatSource: FakeConcatSource,
        },
        NormalModule: {
          getCompilationHooks: vi.fn(() => ({
            loader: {
              tap: (_name: string, handler: (loaderContext: any, module: LoaderModule) => void) => {
                loaderHandler = handler
              },
            },
          })),
        },
      },
      hooks: {
        normalModuleFactory: {
          tap: vi.fn(() => {}),
        },
        compilation: {
          tap: vi.fn((_name: string, handler: (_compilation: any) => void) => {
            handler(compilation)
          }),
        },
      },
    }

    new WeappTailwindcss().apply(compiler as any)
    const sourceCssModule: LoaderModule = {
      loaders: [{ loader: '/path/postcss-loader.js' }],
      resource: '/workspace/src/app.css',
    }
    loaderHandler?.({}, sourceCssModule)
    const rewriteLoaderEntry = sourceCssModule.loaders.find(isCssImportRewriteLoader)
    const loaderRuntime = getWebpackLoaderRuntime(rewriteLoaderEntry?.options?.tailwindcssImportRewriteRuntimeKey)
    loaderRuntime?.cssImportRewrite?.markGeneratedCssSource?.('/workspace/src/app.css')

    await processAssetsCallbacks[0](createAssetsFromStore(assetStore))

    expect(testState.currentContext.styleHandler).not.toHaveBeenCalled()
    expect(assetStore['app.wxss']).not.toContain('handled:')
    expect(assetStore['app.wxss']?.match(new RegExp(`\\.${generatedClass.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'g'))).toHaveLength(1)
  })

})
