// src/navs/documentation.js
// @ts-nocheck
export const documentationNav = {
  // 'Getting Started': [
  //   {
  //     title: 'Installation',
  //     href: '/docs/installation',
  //     match: /^\/docs\/(installation|guides)/,
  //   },
  //   // TODO: Add these pages
  //   // 'tailwind-cli',
  //   // { title: 'Play CDN', href: '#' },
  //   'editor-setup',
  //   'using-with-preprocessors',
  //   'optimizing-for-production',
  //   'browser-support',
  //   'upgrade-guide',
  // ],
  // 'Core Concepts': [
  //   'utility-first',
  //   // TODO: Maybe write this page
  //   // 'writing-your-html',
  //   'hover-focus-and-other-states',
  //   'responsive-design',
  //   'dark-mode',
  //   'reusing-styles',
  //   'adding-custom-styles',
  //   'functions-and-directives',
  // ],
  // Customization: [
  //   'configuration',
  //   'content-configuration',
  //   // TODO: Remove + redirect to v2
  //   // 'just-in-time-mode',
  //   'theme',
  //   'screens',
  //   'customizing-colors',
  //   'customizing-spacing',
  //   // TODO: Redirect to v2
  //   // 'configuring-variants',
  //   'plugins',
  //   'presets',
  // ],
  // 'Base Styles': ['preflight'],
  'Layout': [
    'aspect-ratio',
    // 'container',
    'columns',
    'break-after',
    'break-before',
    'break-inside',
    'box-decoration-break',
    'box-sizing',
    'display',
    'float',
    'clear',
    'isolation',
    'object-fit',
    'object-position',
    'overflow',
    'overscroll-behavior',
    'position',
    'top-right-bottom-left',
    'visibility',
    'z-index',
  ],
  'Flexbox & Grid': [
    'flex-basis',
    'flex-direction',
    'flex-wrap',
    'flex',
    'flex-grow',
    'flex-shrink',
    'order',
    'grid-template-columns',
    'grid-column',
    'grid-template-rows',
    'grid-row',
    'grid-auto-flow',
    'grid-auto-columns',
    'grid-auto-rows',
    'gap',
    'justify-content',
    'justify-items',
    'justify-self',
    'align-content',
    'align-items',
    'align-self',
    'place-content',
    'place-items',
    'place-self',
  ],
  'Spacing': ['padding', 'margin', 'space'],
  'Sizing': [
    'width',
    'min-width',
    'max-width',
    'height',
    'min-height',
    'max-height',
    'size',
  ],
  'Typography': [
    'font-family',
    'font-size',
    'font-smoothing',
    'font-style',
    'font-weight',
    'font-variant-numeric',
    'letter-spacing',
    'line-clamp',
    'line-height',
    'list-style-image',
    'list-style-position',
    'list-style-type',
    'text-align',
    'text-color',
    'text-decoration',
    'text-decoration-color',
    'text-decoration-style',
    'text-decoration-thickness',
    'text-underline-offset',
    'text-transform',
    'text-overflow',
    'text-indent',
    'vertical-align',
    'whitespace',
    'word-break',
    'hyphens',
    'content',
  ],
  'Backgrounds': [
    'background-attachment',
    'background-clip',
    'background-color',
    'background-origin',
    'background-position',
    'background-repeat',
    'background-size',
    'background-image',
    'gradient-color-stops',
  ],
  'Borders': [
    'border-radius',
    'border-width',
    'border-color',
    'border-style',
    'divide-width',
    'divide-color',
    'divide-style',
    'outline-width',
    'outline-color',
    'outline-style',
    'outline-offset',
    'ring-width',
    'ring-color',
    'ring-offset-width',
    'ring-offset-color',
  ],
  'Effects': [
    'box-shadow',
    'box-shadow-color',
    'opacity',
    'mix-blend-mode',
    'background-blend-mode',
  ],
  'Filters': [
    'blur',
    'brightness',
    'contrast',
    'drop-shadow',
    'grayscale',
    'hue-rotate',
    'invert',
    'saturate',
    'sepia',
    'backdrop-blur',
    'backdrop-brightness',
    'backdrop-contrast',
    'backdrop-grayscale',
    'backdrop-hue-rotate',
    'backdrop-invert',
    'backdrop-opacity',
    'backdrop-saturate',
    'backdrop-sepia',
  ],
  'Tables': [
    'border-collapse',
    'border-spacing',
    'table-layout',
    'caption-side',
  ],
  'Transitions & Animation': [
    'transition-property',
    'transition-duration',
    'transition-timing-function',
    'transition-delay',
    'animation',
  ],
  'Transforms': [
    'scale',
    'rotate',
    'translate',
    'skew',
    'transform-origin',
  ],
  'Interactivity': [
    'accent-color',
    'appearance',
    'cursor',
    'caret-color',
    'pointer-events',
    'resize',
    'scroll-behavior',
    'scroll-margin',
    'scroll-padding',
    'scroll-snap-align',
    'scroll-snap-stop',
    'scroll-snap-type',
    'touch-action',
    'user-select',
    'will-change',
  ],
  'SVG': ['fill', 'stroke', 'stroke-width'],
  'Accessibility': ['screen-readers', 'forced-color-adjust'],
  // 'Official Plugins': [
  //   'typography-plugin',
  //   {
  //     title: 'Forms',
  //     href: 'https://github.com/tailwindlabs/tailwindcss-forms',
  //   },
  //   {
  //     title: 'Aspect Ratio',
  //     href: 'https://github.com/tailwindlabs/tailwindcss-aspect-ratio',
  //   },
  //   {
  //     title: 'Container Queries',
  //     href: 'https://github.com/tailwindlabs/tailwindcss-container-queries',
  //   },
  // ],
}
