packages:
  - packages/*
  - packages-runtime/*
  - apps/*
  - website
  - benchmark/*
  - e2e
  - '!tailwindcss-weapp'
  - '!**/test/**'
  - demo/*

catalogs:
  autoprefixer10:
    autoprefixer: ^10.4.23
  babelCore7285:
    '@babel/core': ^7.28.5
  babelPresetReact7285:
    '@babel/preset-react': ^7.28.5
  babelRuntime7284:
    '@babel/runtime': ^7.28.4
  babelRuntime7284tilde:
    '@babel/runtime': ~7.28.4
  crossEnv:
    cross-env: ^10.1.0
  lucideReact0555:
    lucide-react: ^0.562.0
  lucideVueNext0555:
    lucide-vue-next: ^0.562.0
  miniApiTypings:
    miniprogram-api-typings: ^4.1.2
  postcss85:
    postcss: ^8.5.6
  postcssComment2:
    postcss-comment: ^2.0.0
  postcssRem602:
    postcss-rem-to-responsive-pixel: ^7.0.0
  postcssRem610:
    postcss-rem-to-responsive-pixel: ^7.0.0
  postcssRpx:
    postcss-rpx-transform: ^1.0.1
  prettier371:
    prettier: ^3.7.4
  react18:
    '@types/react': ^19.2.7
    '@types/react-dom': 18.2.7
    react: ^18.3.1
    react-dom: ^18.3.1
  react19:
    '@types/react': ^19.2.7
    '@types/react-dom': 19.2.3
    react: ^19.2.3
    react-dom: ^19.2.3
  reactRefresh018:
    react-refresh: ^0.18.0
  sass195:
    sass: ^1.97.2
  stylelint1625:
    stylelint: ^16.26.1
  tailwindMerge:
    tailwind-merge: ^3.4.0
  tailwindcss3:
    tailwindcss: ^3.4.19
  tailwindcss4:
    '@tailwindcss/postcss': ^4.1.18
    '@tailwindcss/vite': ^4.1.18
    tailwindcss: ^4.1.18
    tailwindcss4: npm:tailwindcss@^4.1.17
  tailwindcssPatch:
    tailwindcss-patch: ^8.6.1
  tailwindcssRem:
    tailwindcss-rem2px-preset: ^1.0.3
  taro4:
    '@tarojs/cli': ^4.1.9
    '@tarojs/components': ^4.1.9
    '@tarojs/helper': ^4.1.9
    '@tarojs/plugin-framework-react': ^4.1.9
    '@tarojs/plugin-framework-vue3': ^4.1.9
    '@tarojs/plugin-html': ^4.1.9
    '@tarojs/plugin-platform-alipay': ^4.1.9
    '@tarojs/plugin-platform-h5': ^4.1.9
    '@tarojs/plugin-platform-harmony-hybrid': ^4.1.9
    '@tarojs/plugin-platform-jd': ^4.1.9
    '@tarojs/plugin-platform-qq': ^4.1.9
    '@tarojs/plugin-platform-swan': ^4.1.9
    '@tarojs/plugin-platform-tt': ^4.1.9
    '@tarojs/plugin-platform-weapp': ^4.1.9
    '@tarojs/react': ^4.1.9
    '@tarojs/runtime': ^4.1.9
    '@tarojs/shared': ^4.1.9
    '@tarojs/taro': ^4.1.9
    '@tarojs/taro-loader': ^4.1.9
    '@tarojs/vite-runner': ^4.1.9
    '@tarojs/webpack5-runner': ^4.1.9
    babel-preset-taro: ^4.1.9
    eslint-config-taro: ^4.1.9
  typesNode2410:
    '@types/node': ^24.10.6
  typescript59:
    typescript: ^5.9.3
  typescript59tilde:
    typescript: ~5.9.3
  typescriptEslint849:
    '@typescript-eslint/eslint-plugin': ^8.52.0
    '@typescript-eslint/parser': ^8.52.0
    typescript-eslint: ^8.52.0
  vite5421:
    vite: ^5.4.21
  vite724:
    vite: ^7.3.1
  vue3:
    '@vue/compiler-dom': ^3.5.26
    '@vue/compiler-sfc': ^3.5.26
    vue: ^3.5.26
  vueTsc318:
    vue-tsc: ^3.2.2
  weappChildren:
    weapp-tailwindcss-children: ^0.1.0
  weappIdeCli:
    weapp-ide-cli: ^4.1.2
  weappVite:
    weapp-vite: ^6.1.7
  wrangler4530:
    wrangler: ^4.58.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@tarojs/binding'
  - '@tarojs/cli'
  - '@weapp-tailwindcss/merge'
  - esbuild
  - sharp
  - workerd

packageExtensions:
  '@dcloudio/vue-cli-plugin-hbuilderx@*':
    dependencies:
      '@dcloudio/uni-cli-shared': 2.0.2-4080520251106001
