packages:
  - packages/*
  - plugins/*
  - apps/*
  - website
  - benchmark
  - '!tailwindcss-weapp'
  - '!**/test/**'

catalogs:
  tailwindcss3:
    tailwindcss: ^3.4.17
  tailwindcss4:
    '@tailwindcss/postcss': ^4.1.14
    '@tailwindcss/vite': ^4.1.13
    tailwindcss: ^4.1.13
    tailwindcss4: npm:tailwindcss@^4.1.13

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@tarojs/binding'
  - '@tarojs/cli'
  - esbuild
