packages:
  - .
allowBuilds:
  '@swc/core': true
  esbuild: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - weapp-tailwindcss@5.5.4
  - "@weapp-tailwindcss/postcss@3.3.3"
  - weapp-vite
  - wevu
  - "@weapp-vite/*"
  - "@weapp-core/*"
  - "@wevu/*"
