packages:
  - .
allowBuilds:
  '@parcel/watcher': false
  core-js: false
  core-js-pure: false
  esbuild: true
  fsevents: false
  puppeteer: false
  sharp: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@weapp-tailwindcss/postcss@3.0.4'
  - weapp-tailwindcss@5.0.7
