export const complexSyntaxMap = {
  'Variant chains': [
    'dark:md:hover:[&:not(:first-child)]:underline',
    '[&:has(>img)]:ring-2',
    '[&>*:nth-child(2n+1)]:text-red-500',
    '[&[data-state=open]]:opacity-100',
    'group-[:nth-of-type(3)_&]:block',
    'peer-[:nth-of-type(3)_&]:hidden',
    '[@media(pointer:fine){&:hover}]:opacity-100',
    '[@supports(selector(:has(*)))]:[&:has(>img)]:ring-2',
    'sm:dark:data-[state=open]:hover:[&>svg]:rotate-[180deg]',
    'focus-visible:[&_.icon]:translate-x-[calc(100%-1rem)]',
  ],
  'Data and aria variants': [
    'data-[state=open]:animate-[accordion-down_0.2s_ease-out]',
    'group-data-[state=open]:rotate-180',
    'peer-data-[disabled=true]:opacity-50',
    'aria-[expanded=true]:max-h-[32rem]',
    'group-aria-[sort=ascending]:text-sky-600',
    'peer-aria-[pressed=true]:scale-[0.98]',
  ],
  'Arbitrary values and functions': [
    'w-[calc(100%-theme(spacing.4))]',
    'translate-x-[calc(100%-50%)]',
    'grid-cols-[repeat(auto-fit,minmax(12rem,1fr))]',
    'bg-[linear-gradient(135deg,_#111827,_#1f2937)]',
    'shadow-[0_0_0_1px_rgb(0_0_0_/_0.1),0_10px_30px_-12px_rgb(0_0_0_/_0.35)]',
    'text-[length:var(--step-2)]/7',
    'max-[37.5rem]:[&_.btn-primary]:!px-[clamp(0.75rem,2vw,1rem)]',
    'supports-[backdrop-filter:blur(0)]:backdrop-blur-[12px]',
    'min-[712px]:max-[877px]:right-16',
    'supports-[display:grid]:grid',
  ],
  'Arbitrary properties and content': [
    '[--scroll-offset:calc(theme(spacing.10)-1px)]',
    'lg:[--card-radius:clamp(8px,1.5vw,20px)]',
    '[mask-type:luminance] hover:[mask-type:alpha]',
    '[background:paint(squiggles)]',
    '[clip-path:polygon(0_0,100%_0,100%_100%,0_100%)]',
    'before:content-["hello_world"]',
    'before:content-[attr(data-label)]',
    'after:content-["["]',
    'dark:[&_.card__title]:text-[color:var(--brand-foreground)]',
    'rtl:motion-safe:hover:scale-[1.015]',
  ],
  'Mixed class sets': [
    'dark:md:hover:[&:not(:first-child)]:underline data-[state=open]:opacity-100',
    'min-[712px]:max-[877px]:right-16 supports-[display:grid]:grid',
    'group-aria-[sort=ascending]:text-sky-600 peer-data-[disabled=true]:opacity-50',
    'before:content-["hello_world"] after:content-["["] [clip-path:polygon(0_0,100%_0,100%_100%,0_100%)]',
    '[@media(pointer:fine){&:hover}]:opacity-100 [@supports(selector(:has(*)))]:[&:has(>img)]:ring-2',
  ],
} as const
