export const projects = [
  'react-vite-tailwindcss-v4',
  'vue-vite-tailwindcss-v4',
  'react-rsbuild-tailwindcss-v4',
  'vue-rsbuild-tailwindcss-v4',
  'react-webpack-tailwindcss-v4',
  'vue-webpack-tailwindcss-v4',
]

export const hmrCases = [
  {
    name: 'web react vite Tailwind v4',
    project: 'react-vite-tailwindcss-v4',
    devCommand: ['exec', 'vite', '--host', '127.0.0.1', '--port', '{port}', '--strictPort'],
    sourceFile: 'src/main.tsx',
    titleFrom: 'React Vite Tailwind CSS v4',
    titleTo: 'WEB-HMR-REACT-V4',
    classFrom: '<h1 className="m-0 text-[32px] leading-[38px] font-semibold">',
    classTo: '<h1 data-web-vite-hmr="react-v4" className="m-0 text-[red] leading-[38px] font-semibold">',
    markerAttr: 'react-v4',
  },
  {
    name: 'web vue vite Tailwind v4',
    project: 'vue-vite-tailwindcss-v4',
    devCommand: ['exec', 'vite', '--host', '127.0.0.1', '--port', '{port}', '--strictPort'],
    sourceFile: 'src/App.vue',
    titleFrom: 'Vue Vite Tailwind CSS v4',
    titleTo: 'WEB-HMR-VUE-V4',
    classFrom: '<h1 class="m-0 text-[32px] leading-[38px] font-semibold">',
    classTo: '<h1 data-web-vite-hmr="vue-v4" class="m-0 text-[red] leading-[38px] font-semibold">',
    markerAttr: 'vue-v4',
  },
  {
    name: 'web react rsbuild Tailwind v4',
    project: 'react-rsbuild-tailwindcss-v4',
    devCommand: ['exec', 'rsbuild', 'dev', '--host', '127.0.0.1', '--port', '{port}'],
    readyLog: /ready\s+built/i,
    styleRequired: false,
    sourceFile: 'src/main.tsx',
    titleFrom: 'React Rsbuild Tailwind CSS v4',
    titleTo: 'WEB-HMR-REACT-RSBUILD-V4',
    classFrom: '<h1 className="m-0 text-[32px] leading-[38px] font-semibold">',
    classTo: '<h1 data-web-vite-hmr="react-rsbuild-v4" className="m-0 text-[red] leading-[38px] font-semibold">',
    markerAttr: 'react-rsbuild-v4',
  },
  {
    name: 'web vue rsbuild Tailwind v4',
    project: 'vue-rsbuild-tailwindcss-v4',
    devCommand: ['exec', 'rsbuild', 'dev', '--host', '127.0.0.1', '--port', '{port}'],
    readyLog: /ready\s+built/i,
    styleRequired: false,
    sourceFile: 'src/App.vue',
    titleFrom: 'Vue Rsbuild Tailwind CSS v4',
    titleTo: 'WEB-HMR-VUE-RSBUILD-V4',
    classFrom: '<h1 class="m-0 text-[32px] leading-[38px] font-semibold">',
    classTo: '<h1 data-web-vite-hmr="vue-rsbuild-v4" class="m-0 text-[red] leading-[38px] font-semibold">',
    markerAttr: 'vue-rsbuild-v4',
  },
  {
    name: 'web react webpack Tailwind v4',
    project: 'react-webpack-tailwindcss-v4',
    devCommand: ['exec', 'webpack', 'serve', '--mode', 'development', '--host', '127.0.0.1', '--port', '{port}'],
    sourceFile: 'src/main.tsx',
    titleFrom: 'React Webpack Tailwind CSS v4',
    titleTo: 'WEB-HMR-REACT-WEBPACK-V4',
    classFrom: '<h1 className="m-0 text-[32px] leading-[38px] font-semibold">',
    classTo: '<h1 data-web-vite-hmr="react-webpack-v4" className="m-0 text-[red] leading-[38px] font-semibold">',
    markerAttr: 'react-webpack-v4',
  },
  {
    name: 'web vue webpack Tailwind v4',
    project: 'vue-webpack-tailwindcss-v4',
    devCommand: ['exec', 'webpack', 'serve', '--mode', 'development', '--host', '127.0.0.1', '--port', '{port}'],
    sourceFile: 'src/App.vue',
    titleFrom: 'Vue Webpack Tailwind CSS v4',
    titleTo: 'WEB-HMR-VUE-WEBPACK-V4',
    classFrom: '<h1 class="m-0 text-[32px] leading-[38px] font-semibold">',
    classTo: '<h1 data-web-vite-hmr="vue-webpack-v4" class="m-0 text-[red] leading-[38px] font-semibold">',
    markerAttr: 'vue-webpack-v4',
  },
]
