packages:
  - .

allowBuilds:
  "core-js-pure": false
  sharp: true
  "vue-demi": false

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@weapp-tailwindcss/postcss@3.3.1'
  - weapp-tailwindcss@5.5.0
