packages:
  - .

allowBuilds:
  "core-js-pure": false
  sharp: true
  "vue-demi": false

minimumReleaseAge: 0
minimumReleaseAgeExclude:
  - '@weapp-tailwindcss/*'
  - weapp-vite
  - wevu
  - '@weapp-vite/*'
  - '@weapp-core/*'
  - '@wevu/*'
  - repoctl
  - '@weapp-tailwindcss/postcss@3.3.3'
  - weapp-tailwindcss@5.5.5
