import type { SidebarConfig } from './types'
import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'

const otherInterfaceItemsPathCandidates = [
  path.resolve(process.cwd(), 'docs', 'api', 'other-interfaces.items.json'),
  path.resolve(process.cwd(), 'website', 'docs', 'api', 'other-interfaces.items.json'),
]
const otherInterfaceItemsPath = otherInterfaceItemsPathCandidates.find(fs.existsSync)
const otherInterfaceItems = otherInterfaceItemsPath
  ? JSON.parse(fs.readFileSync(otherInterfaceItemsPath, 'utf8'))
  : []

/**
 * @description 新版本配置项
 */
const API: SidebarConfig = [
  {
    type: 'category',
    label: '配置项',
    link: {
      type: 'doc',
      id: 'api/interfaces/UserDefinedOptions',
    },
    items: [
      {
        type: 'autogenerated',
        dirName: 'api/options',
      },
      {
        type: 'category',
        label: '🗂️ 其他接口',
        link: {
          type: 'doc',
          id: 'api/other-interfaces',
        },
        collapsed: false,
        items: otherInterfaceItems,
      },
    ],
  },
]

export default API
