import type { SidebarConfig } from './types'

/**
 * @description 新版本配置项
 */
const API: SidebarConfig = [
  {
    type: 'autogenerated',
    dirName: 'api', // 'api' is the 'out' directory
  },
]

export default API
