import type { SidebarConfig } from './types'

/**
 * @description 配置项(已经废弃)
 */
const optionsSidebar: SidebarConfig = [
  {
    type: 'doc',
    id: 'api/interfaces/UserDefinedOptions',
    label: '配置项(v3.x)',
  },
  {
    type: 'doc',
    id: 'api-v2/interfaces/UserDefinedOptions',
  },

  // {
  //   type: 'autogenerated',
  //   dirName: 'api', // 'api' is the 'out' directory
  // },
  // {
  //   type: 'doc',
  //   id: 'api/modules.md', // 'api' is the 'out' directory
  // },
]

export default optionsSidebar
