import type { CompatibilityCase } from '../types'

export const visualCases: CompatibilityCase[] = [
  { id: 'type-size', family: 'typography', page: 'visual', title: 'Font size and line height', className: 'text-[length:23px] leading-[1.25]', evidence: 'runtime', probe: 'geometry', declarations: [{ property: 'font-size', value: '23px' }, { property: 'line-height', value: '1.25' }] },
  { id: 'type-weight-style', family: 'typography', page: 'visual', title: 'Weight and style', className: 'font-bold italic', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'font-weight', value: '700' }, { property: 'font-style', value: 'italic' }] },
  { id: 'type-tracking', family: 'typography', page: 'visual', title: 'Letter spacing', className: 'tracking-[0.12em]', evidence: 'runtime', probe: 'geometry', declarations: [{ property: 'letter-spacing', value: '0.12em' }] },
  { id: 'type-align-overflow', family: 'typography', page: 'visual', title: 'Text alignment and overflow', className: 'truncate text-center', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'text-align', value: 'center' }, { property: 'text-overflow', value: 'ellipsis' }] },
  { id: 'type-decoration', family: 'typography', page: 'visual', title: 'Text decoration', className: 'underline decoration-2', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'text-decoration-line', value: 'underline' }, { property: 'text-decoration-thickness', value: '2px' }] },
  { id: 'background-color', family: 'background', page: 'visual', title: 'Background color', className: 'bg-[#123456]', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'background-color', value: '#123456' }] },
  { id: 'background-gradient', family: 'background', page: 'visual', title: 'Gradient', className: 'bg-[radial-gradient(circle_at_20%_20%,#fff,#000)]', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'background-image', value: 'radial-gradient(circle at 20% 20%,#fff,#000)' }] },
  { id: 'background-size', family: 'background', page: 'visual', title: 'Background sizing', className: 'bg-cover bg-center bg-no-repeat', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'background-size', value: 'cover' }, { property: 'background-position', value: 'center' }, { property: 'background-repeat', value: 'no-repeat' }] },
  { id: 'border-width-color', family: 'border', page: 'visual', title: 'Border width and color', className: 'border-2 border-solid border-[#16a34a]', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'border-style', value: 'solid' }, { property: 'border-color', value: '#16a34a' }] },
  { id: 'border-radius', family: 'border', page: 'visual', title: 'Border radius', className: 'rounded-[18px]', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'border-radius', value: '18px' }] },
  { id: 'effect-opacity', family: 'effect', page: 'visual', title: 'Opacity', className: 'opacity-50', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'opacity', value: '50%' }] },
  { id: 'effect-shadow', family: 'effect', page: 'visual', title: 'Box shadow', className: 'shadow-lg', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'box-shadow' }] },
  { id: 'effect-blend', family: 'effect', page: 'visual', title: 'Blend mode', className: 'mix-blend-multiply', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'mix-blend-mode', value: 'multiply' }] },
  { id: 'filter-blur', family: 'filter', page: 'visual', title: 'Blur filter', className: 'blur-[2px]', evidence: 'runtime', probe: 'pixel', declarations: [{ property: '--tw-blur', value: 'blur(2px)' }, { property: 'filter' }] },
  { id: 'filter-backdrop', family: 'filter', page: 'visual', title: 'Backdrop filter', className: 'backdrop-blur-[2px]', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'backdrop-filter' }] },
  { id: 'svg-fill-stroke', family: 'svg', page: 'visual', title: 'SVG fill and stroke', className: 'fill-[#0284c7] stroke-2 stroke-[#0f172a]', evidence: 'runtime', probe: 'pixel', declarations: [{ property: 'fill', value: '#0284c7' }, { property: 'stroke-width', value: '2' }, { property: 'stroke', value: '#0f172a' }] },
  { id: 'accessibility-sr', family: 'accessibility', page: 'visual', title: 'Screen reader only', className: 'sr-only', evidence: 'runtime', probe: 'geometry', declarations: [{ property: 'position', value: 'absolute' }, { property: 'width', value: '1px' }, { property: 'height', value: '1px' }] },
]
