import {
  cleanLocalCssImportWrapperTailwindDirectives,
  cleanLocalCssImportWrapperTailwindDirectivesRoot,
  collectCssImportRequestsRoot,
  createCssSourceOrderAppend,
  isLocalCssImportRequest,
  isMiniProgramLocalCssImportRequest,
  isPureLocalCssImportWrapper,
  isPureLocalCssImportWrapperRoot,
  normalizeOutputImportRequest,
  prefixLocalCssImportsWithWebpackIgnoreRoot,
  postcss,
  restoreLocalCssImports,
  removeTailwindSourceDirectivesRoot,
  removeUnsupportedMiniProgramCssImportsRoot,
  rewriteLocalCssImportRequestsForOutput,
  rewriteLocalCssImportRequestsForOutputRoot,
  splitLocalCssImports,
  splitLocalCssImportsRoot,
} from '@/index'

describe('local css import helpers', () => {
  it('appends css source chunks without adding duplicate whitespace', () => {
    expect(createCssSourceOrderAppend('', '.a{}')).toBe('.a{}')
    expect(createCssSourceOrderAppend('@import "./a.css";', '')).toBe('@import "./a.css";')
    expect(createCssSourceOrderAppend('@import "./a.css";\n', '.a{}')).toBe('@import "./a.css";\n.a{}')
    expect(createCssSourceOrderAppend('@import "./a.css";', ' .a{}')).toBe('@import "./a.css"; .a{}')
  })

  it('detects pure local css import wrappers from strings and roots', () => {
    const css = [
      '/* generated by bundler */',
      '@import "./index.wxss";',
      '@import url("../components/card.css?inline");',
    ].join('\n')

    expect(isPureLocalCssImportWrapper(css)).toBe(true)
    expect(isPureLocalCssImportWrapperRoot(postcss.parse(css))).toBe(true)
  })

  it('rejects non-local and mixed import wrappers', () => {
    expect(isLocalCssImportRequest('./index.css')).toBe(true)
    expect(isLocalCssImportRequest('tailwindcss')).toBe(false)
    expect(isLocalCssImportRequest('weapp-tailwindcss')).toBe(false)
    expect(isLocalCssImportRequest('#app.css')).toBe(false)
    expect(isLocalCssImportRequest('data:text/css,.a{}')).toBe(false)
    expect(isLocalCssImportRequest('https://example.com/app.css')).toBe(false)
    expect(isLocalCssImportRequest('//example.com/app.css')).toBe(false)

    expect(isMiniProgramLocalCssImportRequest('./index.css')).toBe(true)
    expect(isMiniProgramLocalCssImportRequest('/app.wxss')).toBe(true)
    expect(isMiniProgramLocalCssImportRequest('@nutui/nutui-react-taro/dist/style.css')).toBe(false)
    expect(isMiniProgramLocalCssImportRequest('third-party-ui/dist/theme.css')).toBe(false)
    expect(isMiniProgramLocalCssImportRequest('https://example.com/app.css')).toBe(false)

    expect(isPureLocalCssImportWrapper('@import "tailwindcss";')).toBe(false)
    expect(isPureLocalCssImportWrapper('@import "./index.css";\n.btn{color:red}')).toBe(false)
    expect(isPureLocalCssImportWrapper('@import "./index.css"')).toBe(true)
    expect(isPureLocalCssImportWrapperRoot(postcss.root())).toBe(false)
  })

  it('removes unsupported mini-program imports from an existing root', () => {
    const root = postcss.parse([
      '@import "./local.wxss";',
      '@import "/app.wxss";',
      '@import "@nutui/nutui-react-taro/dist/style.css";',
      '@import url("https://example.com/theme.css");',
      '.btn { color: red; }',
    ].join('\n'))

    expect(removeUnsupportedMiniProgramCssImportsRoot(root)).toBe(true)
    expect(root.toString()).toContain('@import "./local.wxss";')
    expect(root.toString()).toContain('@import "/app.wxss";')
    expect(root.toString()).toContain('.btn')
    expect(root.toString()).not.toContain('@nutui')
    expect(root.toString()).not.toContain('https://example.com')
  })

  it('collects import requests from an existing root with optional filtering', () => {
    const root = postcss.parse([
      '@import "./local.wxss";',
      '@import url("../theme.acss?inline");',
      '@import "third-party-ui/dist/theme.css";',
      '@import "https://example.com/theme.css";',
    ].join('\n'))

    expect([...collectCssImportRequestsRoot(root)]).toEqual([
      './local.wxss',
      '../theme.acss?inline',
      'third-party-ui/dist/theme.css',
      'https://example.com/theme.css',
    ])
    expect([...collectCssImportRequestsRoot(root, {
      isSupportedImportRequest: isMiniProgramLocalCssImportRequest,
    })]).toEqual([
      './local.wxss',
      '../theme.acss?inline',
    ])
  })

  it('removes Tailwind source directives while preserving non-empty user layers', () => {
    const root = postcss.parse([
      '@import "tailwindcss";',
      '@import "#tailwindcss";',
      '@source "./src";',
      '@theme { --color-brand: red; }',
      '@layer utilities;',
      '@layer components { .btn { color: red; } }',
    ].join('\n'))

    expect(removeTailwindSourceDirectivesRoot(root)).toBe(true)
    expect(root.toString()).toContain('@layer components')
    expect(root.toString()).toContain('.btn')
    expect(root.toString()).not.toContain('@import "tailwindcss"')
    expect(root.toString()).not.toContain('@source')
    expect(root.toString()).not.toContain('@theme')
    expect(root.toString()).not.toContain('@layer utilities')
  })

  it('prefixes local imports with webpack ignore comments from a parsed root', () => {
    const root = postcss.parse('@import "./a.css";\n@import "tailwindcss";')

    expect(prefixLocalCssImportsWithWebpackIgnoreRoot(root)).toBe(true)
    expect(root.toString()).toBe('/* webpackIgnore: true */\n@import "./a.css";\n@import "tailwindcss";')
  })

  it('splits local imports from the source while keeping other imports in place', () => {
    const css = [
      '@import "./base.css";',
      '@import "tailwindcss";',
      '@import url("../theme.wxss");',
      '.btn { color: red; }',
    ].join('\n')

    expect(splitLocalCssImports(css)).toEqual({
      imports: '@import "./base.css";\n@import url("../theme.wxss");',
      source: [
        '@import "tailwindcss";',
        '.btn { color: red; }',
      ].join('\n'),
    })

    const root = postcss.parse(css)
    expect(splitLocalCssImportsRoot(root)).toEqual({
      imports: '@import "./base.css";\n@import url("../theme.wxss");',
      source: [
        '@import "tailwindcss";',
        '.btn { color: red; }',
      ].join('\n'),
    })
  })

  it('restores local imports before generated css', () => {
    expect(restoreLocalCssImports('.btn{color:red}', '@import "./base.css";')).toBe([
      '@import "./base.css";',
      '.btn{color:red}',
    ].join('\n'))
    expect(restoreLocalCssImports('.uvue{}', [
      '@import "/uvue.wxss";',
      '@import "./shared.wxss";',
    ].join('\n'), { outputFile: 'uvue.wxss' })).toBe([
      '@import "./shared.wxss";',
      '.uvue{}',
    ].join('\n'))
    expect(restoreLocalCssImports('.page{}', [
      '@import "./index.wxss";',
      '@import "../shared.wxss";',
    ].join('\n'), { outputFile: 'pages/index.wxss' })).toBe([
      '@import "../shared.wxss";',
      '.page{}',
    ].join('\n'))
    expect(restoreLocalCssImports('.btn{color:red}', undefined)).toBe('.btn{color:red}')
  })

  it('cleans Tailwind source directives from local import wrappers in one parsed root', () => {
    const css = [
      '@import "./index.wxss";',
      '@source "../src";',
    ].join('\n')

    expect(cleanLocalCssImportWrapperTailwindDirectives(css)).toBe([
      '/* webpackIgnore: true */',
      '@import "./index.wxss";',
    ].join('\n'))

    const root = postcss.parse(css)
    expect(cleanLocalCssImportWrapperTailwindDirectivesRoot(root)).toBe(true)
    expect(root.toString()).toBe([
      '/* webpackIgnore: true */',
      '@import "./index.wxss";',
    ].join('\n'))
  })

  it('does not clean mixed wrapper css', () => {
    expect(cleanLocalCssImportWrapperTailwindDirectives([
      '@import "./index.wxss";',
      '@source "../src";',
      '.btn { color: red; }',
    ].join('\n'))).toBeUndefined()
    expect(cleanLocalCssImportWrapperTailwindDirectives('@import "./index.wxss"')).toBeUndefined()
    expect(cleanLocalCssImportWrapperTailwindDirectives('@import "./index.wxss";')).toBeUndefined()
    expect(cleanLocalCssImportWrapperTailwindDirectives('@source "./src";')).toBeUndefined()
  })

  it('rewrites local source import requests for emitted output extensions', () => {
    expect(normalizeOutputImportRequest('.\\src\\theme.less#dark', 'wxss')).toBe('./theme.wxss#dark')
    expect(normalizeOutputImportRequest('./theme.wxss', undefined)).toBe('./theme.wxss')
    expect(rewriteLocalCssImportRequestsForOutput(
      '@import "./src/third-party-ui.css";\n.foo{color:red}',
      { styleOutputExtension: '.wxss' },
    )).toBe('@import "./third-party-ui.wxss";\n.foo{color:red}')
    expect(rewriteLocalCssImportRequestsForOutput(
      '@import "./styles/third-party-ui.css?inline";',
      { styleOutputExtension: 'acss' },
    )).toBe('@import "./styles/third-party-ui.acss?inline";')
    expect(rewriteLocalCssImportRequestsForOutput(
      '@import "https://example.com/theme.css";',
      { styleOutputExtension: 'wxss' },
    )).toBe('@import "https://example.com/theme.css";')
    expect(rewriteLocalCssImportRequestsForOutput('.foo{color:red}', { styleOutputExtension: 'wxss' })).toBe('.foo{color:red}')
    expect(rewriteLocalCssImportRequestsForOutput('@import "./broken.css"', { styleOutputExtension: 'wxss' })).toBe('@import "./broken.wxss"')
  })

  it('rewrites import requests from an existing root without reparsing', () => {
    const root = postcss.parse('@import "./src/index.scss#theme";\n@import "tailwindcss";')

    expect(rewriteLocalCssImportRequestsForOutputRoot(root, {
      styleOutputExtension: 'ttss',
    })).toBe(true)
    expect(root.toString()).toBe('@import "./index.ttss#theme";\n@import "tailwindcss";')
  })
})
