import {
  cleanLocalCssImportWrapperTailwindDirectives,
  cleanLocalCssImportWrapperTailwindDirectivesRoot,
  isLocalCssImportRequest,
  isPureLocalCssImportWrapper,
  isPureLocalCssImportWrapperRoot,
  postcss,
  restoreLocalCssImports,
  rewriteLocalCssImportRequestsForOutput,
  rewriteLocalCssImportRequestsForOutputRoot,
  splitLocalCssImports,
  splitLocalCssImportsRoot,
} from '@/index'

describe('local css import helpers', () => {
  it('detects pure local css import wrappers from strings and roots', () => {
    const css = [
      '/* generated by bundler */',
      '@import "./index.wxss";',
      '@import url("../components/card.css?inline");',
    ].join('\n')

    expect(isPureLocalCssImportWrapper(css)).toBe(true)
    expect(isPureLocalCssImportWrapperRoot(postcss.parse(css))).toBe(true)
  })

  it('rejects non-local and mixed import wrappers', () => {
    expect(isLocalCssImportRequest('./index.css')).toBe(true)
    expect(isLocalCssImportRequest('tailwindcss')).toBe(false)
    expect(isLocalCssImportRequest('weapp-tailwindcss')).toBe(false)
    expect(isLocalCssImportRequest('#app.css')).toBe(false)
    expect(isLocalCssImportRequest('data:text/css,.a{}')).toBe(false)
    expect(isLocalCssImportRequest('https://example.com/app.css')).toBe(false)
    expect(isLocalCssImportRequest('//example.com/app.css')).toBe(false)

    expect(isPureLocalCssImportWrapper('@import "tailwindcss";')).toBe(false)
    expect(isPureLocalCssImportWrapper('@import "./index.css";\n.btn{color:red}')).toBe(false)
  })

  it('splits local imports from the source while keeping other imports in place', () => {
    const css = [
      '@import "./base.css";',
      '@import "tailwindcss";',
      '@import url("../theme.wxss");',
      '.btn { color: red; }',
    ].join('\n')

    expect(splitLocalCssImports(css)).toEqual({
      imports: '@import "./base.css";\n@import url("../theme.wxss");',
      source: [
        '@import "tailwindcss";',
        '.btn { color: red; }',
      ].join('\n'),
    })

    const root = postcss.parse(css)
    expect(splitLocalCssImportsRoot(root)).toEqual({
      imports: '@import "./base.css";\n@import url("../theme.wxss");',
      source: [
        '@import "tailwindcss";',
        '.btn { color: red; }',
      ].join('\n'),
    })
  })

  it('restores local imports before generated css', () => {
    expect(restoreLocalCssImports('.btn{color:red}', '@import "./base.css";')).toBe([
      '@import "./base.css";',
      '.btn{color:red}',
    ].join('\n'))
    expect(restoreLocalCssImports('.btn{color:red}', undefined)).toBe('.btn{color:red}')
  })

  it('cleans Tailwind source directives from local import wrappers in one parsed root', () => {
    const css = [
      '@import "./index.wxss";',
      '@source "../src";',
    ].join('\n')

    expect(cleanLocalCssImportWrapperTailwindDirectives(css)).toBe([
      '/* webpackIgnore: true */',
      '@import "./index.wxss";',
    ].join('\n'))

    const root = postcss.parse(css)
    expect(cleanLocalCssImportWrapperTailwindDirectivesRoot(root)).toBe(true)
    expect(root.toString()).toBe([
      '/* webpackIgnore: true */',
      '@import "./index.wxss";',
    ].join('\n'))
  })

  it('does not clean mixed wrapper css', () => {
    expect(cleanLocalCssImportWrapperTailwindDirectives([
      '@import "./index.wxss";',
      '@source "../src";',
      '.btn { color: red; }',
    ].join('\n'))).toBeUndefined()
  })

  it('rewrites local source import requests for emitted output extensions', () => {
    expect(rewriteLocalCssImportRequestsForOutput(
      '@import "./src/third-party-ui.css";\n.foo{color:red}',
      { styleOutputExtension: '.wxss' },
    )).toBe('@import "./third-party-ui.wxss";\n.foo{color:red}')
    expect(rewriteLocalCssImportRequestsForOutput(
      '@import "./styles/third-party-ui.css?inline";',
      { styleOutputExtension: 'acss' },
    )).toBe('@import "./styles/third-party-ui.acss?inline";')
    expect(rewriteLocalCssImportRequestsForOutput(
      '@import "https://example.com/theme.css";',
      { styleOutputExtension: 'wxss' },
    )).toBe('@import "https://example.com/theme.css";')
  })

  it('rewrites import requests from an existing root without reparsing', () => {
    const root = postcss.parse('@import "./src/index.scss#theme";\n@import "tailwindcss";')

    expect(rewriteLocalCssImportRequestsForOutputRoot(root, {
      styleOutputExtension: 'ttss',
    })).toBe(true)
    expect(root.toString()).toBe('@import "./index.ttss#theme";\n@import "tailwindcss";')
  })
})
