import { defineComponent } from "vue";

import { onLoad } from '@dcloudio/uni-app';
export default defineComponent({
    data() {
        return {
            title: 'Hello'
        };
    },
    onLoad() {
    },
    methods: {}
});
//# sourceMappingURL=/Users/yangqiming/Documents/GitHub/weapp-tailwindcss/apps/uni-app-x-hbuilderx-tailwindcss3/pages/index/index.uvue?vue&type=script&lang.uts.js.map