# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "development"
	lane :build_dev do |options|
		update_info_plist
		update_code_signing_settings
		increment_version_number
		build_app(
			scheme: "taroDemo",
			workspace: "taroDemo.xcworkspace",
			export_method: "development",
			configuration: "Debug",
			clean: true,
			xcargs: "GCC_PREPROCESSOR_DEFINITIONS='$(inherited) DEBUG=1'",
			export_options: {
				method: "development",
				compileBitcode: false
			}
		)
	end

	desc "release"
	lane :build_release do |options|
		update_info_plist
		update_code_signing_settings
		increment_version_number
		increment_build_number
		build_app(
			scheme: "taroDemo",
			# clean: true,
			workspace: "taroDemo.xcworkspace"
		)
	end
	
end
