export interface CssSummary {
  bytes: number
  selectors: string[]
  hasSupports: boolean
  hasHoverPseudo: boolean
  hasTailwindBanner: boolean
  hasSystemDarkModeMedia: boolean
  hasManualDarkModeSelector: boolean
  hasUnsupportedThemeAttributeSelector: boolean
  hasUnsupportedThemeComplexSelector: boolean
  hasWeappEscapedArbitrarySelector: boolean
  hasRawArbitrarySelector: boolean
}

export interface CompareReportItem {
  name: string
  fixture: 'demo'
  platform: string
  allowedPlatforms: string[]
  cssFile: string
  cssFiles: string[]
  status: 'passed'
  generator: CssSummary
}

export interface FailedCompareReportItem {
  name: string
  fixture: 'demo'
  platform: string
  allowedPlatforms: string[]
  cssFile: string
  cssFiles: string[]
  status: 'failed'
  error: string
}

export type AppsGeneratorCompareReportItem = CompareReportItem | FailedCompareReportItem

function formatBoolean(value: boolean) {
  return value ? 'yes' : 'no'
}

function formatChineseBoolean(value: boolean) {
  return value ? '是' : '否'
}

function formatSelectorList(selectors: string[]) {
  if (selectors.length === 0) {
    return '-'
  }
  return selectors.slice(0, 20).map(selector => `\`${selector.replaceAll('|', '\\|')}\``).join(', ')
}

function formatCssFiles(item: AppsGeneratorCompareReportItem) {
  if (item.cssFiles.length <= 1) {
    return `\`${item.cssFile}\``
  }
  return `\`${item.cssFile}\` (+${item.cssFiles.length - 1})`
}

function formatPlatformList(platforms: string[]) {
  if (platforms.length === 0) {
    return '-'
  }
  return platforms.map(platform => `\`${platform.replaceAll('|', '\\|')}\``).join(', ')
}

export function createMarkdownReport(report: AppsGeneratorCompareReportItem[]) {
  const lines: string[] = [
    '# Demo Generator Mode CSS Output',
    '',
    'This report is generated by `pnpm e2e:apps-generator`. It builds each retained demo with the default generator path and checks CSS output by platform.',
    '',
    '## Summary',
    '',
    '| Project | Fixture | Platform | Allowed platforms | Status | CSS | Bytes | Selectors | @supports | :hover | Tailwind banner | System dark media | Manual dark selector | Unsupported theme attribute selector | Unsupported theme complex selector | Raw arbitrary selector | Weapp escaped arbitrary selector |',
    '| --- | --- | --- | --- | --- | --- | ---: | ---: | --- | --- | --- | --- | --- | --- | --- | --- | --- |',
  ]

  for (const item of report) {
    if (item.status === 'failed') {
      lines.push(
        [
          item.name,
          item.fixture,
          item.platform,
          formatPlatformList(item.allowedPlatforms),
          'failed',
          formatCssFiles(item),
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
        ].join(' | ').replace(/^/, '| ').replace(/$/, ' |'),
      )
      continue
    }

    lines.push(
      [
        item.name,
        item.fixture,
        item.platform,
        formatPlatformList(item.allowedPlatforms),
        item.status,
        formatCssFiles(item),
        item.generator.bytes,
        item.generator.selectors.length,
        formatBoolean(item.generator.hasSupports),
        formatBoolean(item.generator.hasHoverPseudo),
        formatBoolean(item.generator.hasTailwindBanner),
        formatBoolean(item.generator.hasSystemDarkModeMedia),
        formatBoolean(item.generator.hasManualDarkModeSelector),
        formatBoolean(item.generator.hasUnsupportedThemeAttributeSelector),
        formatBoolean(item.generator.hasUnsupportedThemeComplexSelector),
        formatBoolean(item.generator.hasRawArbitrarySelector),
        formatBoolean(item.generator.hasWeappEscapedArbitrarySelector),
      ].join(' | ').replace(/^/, '| ').replace(/$/, ' |'),
    )
  }

  lines.push(
    '',
    '## Notes',
    '',
    '- CSS column shows the entry stylesheet. `(+N)` means the report also aggregates `@import`-linked stylesheets, such as Taro `app-origin.wxss` or Mpx hashed `styles/app*.wxss`.',
    '- Platform is the target built by the default demo `build` script. Allowed platforms come from `DEMO_COVERAGE_MATRIX` and are listed so platform-specific outputs can be compared in separate folders.',
    '- `@supports`, `:hover`, and Tailwind banner columns describe the generator output. They should stay `no` for mini-program compatibility.',
    '- System dark media and manual dark selector columns confirm `prefers-color-scheme` and `.theme-dark` class examples both survive generator mode.',
    '- Selector lists show the first 20 entries to keep the report stable and readable.',
    '- Failed rows keep the first error message in the failure section so migration blockers stay visible.',
    '',
    '## Failures',
    '',
    ...formatFailures(report, false),
    '',
    '## Selector Samples',
    '',
  )

  for (const item of report) {
    if (item.status === 'failed') {
      continue
    }
    lines.push(
      `### ${item.name}`,
      '',
      `- CSS files: ${item.cssFiles.map(file => `\`${file.replaceAll('|', '\\|')}\``).join(', ')}`,
      `- Selectors: ${formatSelectorList(item.generator.selectors)}`,
      '',
    )
  }

  return `${lines.join('\n').trimEnd()}\n`
}

function formatFailures(report: AppsGeneratorCompareReportItem[], chinese: boolean) {
  const failures = report.filter((item): item is FailedCompareReportItem => item.status === 'failed')
  if (failures.length === 0) {
    return [chinese ? '- 无' : '- None']
  }
  return failures.map((item) => {
    const message = item.error.replace(/\s+/g, ' ').trim()
    return chinese
      ? `- \`${item.name}\` 失败：${message}`
      : `- \`${item.name}\` failed: ${message}`
  })
}

export function createChineseMarkdownReport(report: AppsGeneratorCompareReportItem[]) {
  const lines: string[] = [
    '# Demo 生成模式 CSS 产物报告',
    '',
    '本报告由 `pnpm e2e:apps-generator` 生成，用来按平台验证保留的 demo 在默认生成模式下的样式产物。',
    '',
    '## 汇总',
    '',
    '| 项目 | 来源 | 平台 | 允许平台 | 状态 | CSS 文件 | 字节数 | 选择器数 | @supports | :hover | Tailwind banner | 系统暗色媒体查询 | 手动暗色选择器 | 不兼容主题属性选择器 | 不兼容主题复杂选择器 | 原始任意值选择器 | 小程序转义任意值选择器 |',
    '| --- | --- | --- | --- | --- | --- | ---: | ---: | --- | --- | --- | --- | --- | --- | --- | --- | --- |',
  ]

  for (const item of report) {
    if (item.status === 'failed') {
      lines.push(
        [
          item.name,
          item.fixture,
          item.platform,
          formatPlatformList(item.allowedPlatforms),
          '失败',
          formatCssFiles(item),
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
        ].join(' | ').replace(/^/, '| ').replace(/$/, ' |'),
      )
      continue
    }

    lines.push(
      [
        item.name,
        item.fixture,
        item.platform,
        formatPlatformList(item.allowedPlatforms),
        item.status === 'passed' ? '通过' : item.status,
        formatCssFiles(item),
        item.generator.bytes,
        item.generator.selectors.length,
        formatChineseBoolean(item.generator.hasSupports),
        formatChineseBoolean(item.generator.hasHoverPseudo),
        formatChineseBoolean(item.generator.hasTailwindBanner),
        formatChineseBoolean(item.generator.hasSystemDarkModeMedia),
        formatChineseBoolean(item.generator.hasManualDarkModeSelector),
        formatChineseBoolean(item.generator.hasUnsupportedThemeAttributeSelector),
        formatChineseBoolean(item.generator.hasUnsupportedThemeComplexSelector),
        formatChineseBoolean(item.generator.hasRawArbitrarySelector),
        formatChineseBoolean(item.generator.hasWeappEscapedArbitrarySelector),
      ].join(' | ').replace(/^/, '| ').replace(/$/, ' |'),
    )
  }

  lines.push(
    '',
    '## 说明',
    '',
    '- CSS 文件列展示入口样式；`(+N)` 表示报告还会聚合 `@import` 关联样式，例如 Taro 的 `app-origin.wxss` 或 Mpx 的 hash 化 `styles/app*.wxss`。',
    '- 平台列表示默认 demo `build` 脚本实际构建的目标；允许平台来自 `DEMO_COVERAGE_MATRIX`，用于把后续多平台产物放入不同目录进行对比。',
    '- `@supports`、`:hover` 和 Tailwind banner 三列描述的是生成模式产物。面向小程序时这些值应保持为 `否`。',
    '- 系统暗色媒体查询和手动暗色选择器两列用于确认 `prefers-color-scheme` 与 `.theme-dark` class 示例都进入生成模式产物。',
    '- 选择器列表会展示前 20 项，便于观察生成模式是否覆盖当前 demo 的有效类名。',
    '- 失败行会在失败详情中保留首个错误信息，便于持续消除迁移阻塞。',
    '',
    '## 失败详情',
    '',
    ...formatFailures(report, true),
    '',
    '## 选择器样本',
    '',
  )

  for (const item of report) {
    if (item.status === 'failed') {
      continue
    }
    lines.push(
      `### ${item.name}`,
      '',
      `- CSS 文件：${item.cssFiles.map(file => `\`${file.replaceAll('|', '\\|')}\``).join(', ')}`,
      `- 选择器：${formatSelectorList(item.generator.selectors)}`,
      '',
    )
  }

  return `${lines.join('\n').trimEnd()}\n`
}
