export interface CssSummary {
  bytes: number
  selectors: string[]
  hasSupports: boolean
  hasHoverPseudo: boolean
  hasTailwindBanner: boolean
  hasWeappEscapedArbitrarySelector: boolean
  hasRawArbitrarySelector: boolean
}

export interface CompareReportItem {
  name: string
  fixture: 'apps' | 'demo'
  cssFile: string
  cssFiles: string[]
  status: 'passed'
  legacy: CssSummary
  generator: CssSummary
  deltaBytes: number
  generatorBytesRatio: number
  sharedSelectors: string[]
  generatorOnlySelectors: string[]
  legacyOnlySelectors: string[]
}

export interface FailedCompareReportItem {
  name: string
  fixture: 'apps' | 'demo'
  cssFile: string
  cssFiles: string[]
  status: 'failed'
  failedMode: 'legacy' | 'generator'
  error: string
}

export type AppsGeneratorCompareReportItem = CompareReportItem | FailedCompareReportItem

function formatBoolean(value: boolean) {
  return value ? 'yes' : 'no'
}

function formatChineseBoolean(value: boolean) {
  return value ? '是' : '否'
}

function formatSigned(value: number) {
  return value > 0 ? `+${value}` : String(value)
}

function formatSelectorList(selectors: string[]) {
  if (selectors.length === 0) {
    return '-'
  }
  return selectors.slice(0, 20).map(selector => `\`${selector.replaceAll('|', '\\|')}\``).join(', ')
}

function formatSelectorCount(selectors: string[], chinese: boolean) {
  if (selectors.length === 0) {
    return chinese ? '无' : 'none'
  }
  return chinese ? `需要兼容（${selectors.length}）` : `needs compat (${selectors.length})`
}

function formatCssFiles(item: AppsGeneratorCompareReportItem) {
  if (item.cssFiles.length <= 1) {
    return `\`${item.cssFile}\``
  }
  return `\`${item.cssFile}\` (+${item.cssFiles.length - 1})`
}

export function createMarkdownReport(report: AppsGeneratorCompareReportItem[]) {
  const lines: string[] = [
    '# Apps Generator Mode CSS Comparison',
    '',
    'This report is generated by `pnpm e2e:apps-generator`. It compares each demo app built with `WEAPP_TW_GENERATOR_MODE=legacy` and `WEAPP_TW_GENERATOR_MODE=generator`.',
    '',
    '## Summary',
    '',
    '| Project | Fixture | Status | CSS | Legacy bytes | Generator bytes | Delta | Ratio | Legacy only | @supports | :hover | Tailwind banner |',
    '| --- | --- | --- | --- | ---: | ---: | ---: | ---: | --- | --- | --- | --- |',
  ]

  for (const item of report) {
    if (item.status === 'failed') {
      lines.push(
        [
          item.name,
          item.fixture,
          `failed (${item.failedMode})`,
          formatCssFiles(item),
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
        ].join(' | ').replace(/^/, '| ').replace(/$/, ' |'),
      )
      continue
    }

    lines.push(
      [
        item.name,
        item.fixture,
        item.status,
        formatCssFiles(item),
        item.legacy.bytes,
        item.generator.bytes,
        formatSigned(item.deltaBytes),
        item.generatorBytesRatio,
        formatSelectorCount(item.legacyOnlySelectors, false),
        formatBoolean(item.generator.hasSupports),
        formatBoolean(item.generator.hasHoverPseudo),
        formatBoolean(item.generator.hasTailwindBanner),
      ].join(' | ').replace(/^/, '| ').replace(/$/, ' |'),
    )
  }

  lines.push(
    '',
    '## Notes',
    '',
    '- CSS column shows the entry stylesheet. `(+N)` means the report also aggregates `@import`-linked stylesheets, such as Taro `app-origin.wxss` or Mpx hashed `styles/app*.wxss`.',
    '- `@supports`, `:hover`, and Tailwind banner columns describe the generator output. They should stay `no` for mini-program compatibility.',
    '- `Delta` is `generator bytes - legacy bytes`. Positive values mean the generator output is currently larger; the selector samples below make that difference visible for follow-up optimization.',
    '- `Legacy only` must stay `none`. Non-zero values mean legacy CSS selectors still need generator output or compat CSS coverage.',
    '- Selector lists show the first 20 entries to keep the report stable and readable.',
    '- Failed rows keep the first failing mode and error message in the failure section so migration blockers stay visible.',
    '',
    '## Failures',
    '',
    ...formatFailures(report, false),
    '',
    '## Selector Samples',
    '',
  )

  for (const item of report) {
    if (item.status === 'failed') {
      continue
    }
    lines.push(
      `### ${item.name}`,
      '',
      `- CSS files: ${item.cssFiles.map(file => `\`${file.replaceAll('|', '\\|')}\``).join(', ')}`,
      `- Shared selectors: ${formatSelectorList(item.sharedSelectors)}`,
      `- Generator only: ${formatSelectorList(item.generatorOnlySelectors)}`,
      `- Legacy only: ${formatSelectorList(item.legacyOnlySelectors)}`,
      '',
    )
  }

  return `${lines.join('\n').trimEnd()}\n`
}

function formatFailures(report: AppsGeneratorCompareReportItem[], chinese: boolean) {
  const failures = report.filter((item): item is FailedCompareReportItem => item.status === 'failed')
  if (failures.length === 0) {
    return [chinese ? '- 无' : '- None']
  }
  return failures.map((item) => {
    const message = item.error.replace(/\s+/g, ' ').trim()
    return chinese
      ? `- \`${item.name}\` 在 \`${item.failedMode}\` 模式失败：${message}`
      : `- \`${item.name}\` failed in \`${item.failedMode}\` mode: ${message}`
  })
}

export function createChineseMarkdownReport(report: AppsGeneratorCompareReportItem[]) {
  const lines: string[] = [
    '# Apps 生成模式 CSS 对比报告',
    '',
    '本报告由 `pnpm e2e:apps-generator` 生成，用来对比 demo app 在 `WEAPP_TW_GENERATOR_MODE=legacy` 和 `WEAPP_TW_GENERATOR_MODE=generator` 两种构建模式下的样式产物。',
    '',
    '## 汇总',
    '',
    '| 项目 | 来源 | 状态 | CSS 文件 | 旧链路字节数 | 生成模式字节数 | 差值 | 比例 | 旧链路独有 | @supports | :hover | Tailwind banner |',
    '| --- | --- | --- | --- | ---: | ---: | ---: | ---: | --- | --- | --- | --- |',
  ]

  for (const item of report) {
    if (item.status === 'failed') {
      lines.push(
        [
          item.name,
          item.fixture,
          `失败（${item.failedMode}）`,
          formatCssFiles(item),
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
          '-',
        ].join(' | ').replace(/^/, '| ').replace(/$/, ' |'),
      )
      continue
    }

    lines.push(
      [
        item.name,
        item.fixture,
        item.status === 'passed' ? '通过' : item.status,
        formatCssFiles(item),
        item.legacy.bytes,
        item.generator.bytes,
        formatSigned(item.deltaBytes),
        item.generatorBytesRatio,
        formatSelectorCount(item.legacyOnlySelectors, true),
        formatChineseBoolean(item.generator.hasSupports),
        formatChineseBoolean(item.generator.hasHoverPseudo),
        formatChineseBoolean(item.generator.hasTailwindBanner),
      ].join(' | ').replace(/^/, '| ').replace(/$/, ' |'),
    )
  }

  lines.push(
    '',
    '## 说明',
    '',
    '- CSS 文件列展示入口样式；`(+N)` 表示报告还会聚合 `@import` 关联样式，例如 Taro 的 `app-origin.wxss` 或 Mpx 的 hash 化 `styles/app*.wxss`。',
    '- `@supports`、`:hover` 和 Tailwind banner 三列描述的是生成模式产物。面向小程序时这些值应保持为 `否`。',
    '- `差值` 等于 `生成模式字节数 - 旧链路字节数`。正数表示当前生成模式产物更大；下面的选择器样本可用于定位后续需要裁剪的部分。',
    '- `旧链路独有` 必须保持为 `无`。非零值表示旧链路选择器仍需要生成模式产出或兼容 CSS 覆盖。',
    '- 选择器列表会展示前 20 项；`仅旧链路` 的完整数量会在汇总表标出，便于持续清零。',
    '- 失败行会在失败详情中保留首个失败模式和错误信息，便于持续消除迁移阻塞。',
    '',
    '## 失败详情',
    '',
    ...formatFailures(report, true),
    '',
    '## 选择器样本',
    '',
  )

  for (const item of report) {
    if (item.status === 'failed') {
      continue
    }
    lines.push(
      `### ${item.name}`,
      '',
      `- CSS 文件：${item.cssFiles.map(file => `\`${file.replaceAll('|', '\\|')}\``).join(', ')}`,
      `- 两边共有：${formatSelectorList(item.sharedSelectors)}`,
      `- 仅生成模式：${formatSelectorList(item.generatorOnlySelectors)}`,
      `- 仅旧链路：${formatSelectorList(item.legacyOnlySelectors)}`,
      '',
    )
  }

  return `${lines.join('\n').trimEnd()}\n`
}
