import { describe, expect, it } from 'vitest'
import { normalizeCssSnapshot } from './snapshotUtils'

describe('normalizeCssSnapshot', () => {
  it('removes scanner noise utilities without a class list', () => {
    expect(normalizeCssSnapshot([
      ':host { --color-red-500: red; --spacing: 8rpx; }',
      '/*$vite$:1*/',
      '.start { left: var(--spacing); }',
      '.end { right: var(--spacing); }',
      '.border-bs { border-top-width: 1px; }',
      '.border-be { border-bottom-width: 1px; }',
      '.text-_b45rpx_B { font-size: 45rpx; }',
    ].join('\n'))).toBe([
      ':host { --spacing: 8rpx; }',
      '.text-_b45rpx_B { font-size: 45rpx; }',
    ].join('\n'))
  })

  it('removes scanner noise utilities even when class list contains them', () => {
    expect(normalizeCssSnapshot([
      ':host { --spacing: 8rpx; }',
      '/*$vite$:1*/',
      '.start { left: var(--spacing); }',
      '.end { right: var(--spacing); }',
      '.border-bs { border-top-width: 1px; }',
      '.border-be { border-bottom-width: 1px; }',
      '.text-_b45rpx_B { font-size: 45rpx; }',
    ].join('\n'), {
      classList: ['start', 'end', 'border-bs', 'border-be', 'text-_b45rpx_B'],
    })).toBe([
      ':host { --spacing: 8rpx; }',
      '.text-_b45rpx_B { font-size: 45rpx; }',
    ].join('\n'))
  })

  it('removes fallback declarations before equivalent var declarations', () => {
    expect(normalizeCssSnapshot([
      '.rounded-md {',
      '  border-radius: 12rpx;',
      '  border-radius: var(--radius-md);',
      '}',
      '.border-b-_b4rpx_B {',
      '  border-bottom-style: var(--tw-border-style);',
      '  border-bottom-width: 4rpx;',
      '}',
    ].join('\n'))).toBe([
      '.rounded-md {',
      '  border-radius: var(--radius-md);',
      '}',
      '.border-b-_b4rpx_B {',
      '  border-bottom-width: 4rpx;',
      '}',
    ].join('\n'))
  })

  it('normalizes calc wrapper and utility rule ordering differences', () => {
    expect(normalizeCssSnapshot([
      ':host { --spacing: 8rpx; --color-red-500: red; }',
      '.border-t-_b4px_B { border-top-width: 4px; }',
      '.border-_b_h098765_B { border-color: #098765; }',
      '.border-_b10rpx_B { border-width: 10rpx; }',
      '.border-_bred_B { border-color: red; }',
      '.border-b-_b4rpx_B { border-bottom-width: 4rpx; }',
      '.text-_b32px_B { font-size: 32px; }',
      '.text-_b32_d4rpx_B { font-size: 32.4rpx; }',
      '.text-_b32rpx_B { font-size: 32rpx; }',
      '.divide-x-8 {',
      '  border-left-width: calc(8rpx * calc(1 - var(--tw-divide-x-reverse)));',
      '  border-left-width: calc(8rpx * (1 - var(--tw-divide-x-reverse)));',
      '}',
    ].join('\n'))).toBe([
      ':host { --spacing: 8rpx; }',
      '.border-_b10rpx_B { border-width: 10rpx; }',
      '.border-_b_h098765_B { border-color: #098765; }',
      '.border-_bred_B { border-color: red; }',
      '.border-b-_b4rpx_B { border-bottom-width: 4rpx; }',
      '.border-t-_b4px_B { border-top-width: 4px; }',
      '.text-_b32_d4rpx_B { font-size: 32.4rpx; }',
      '.text-_b32px_B { font-size: 32px; }',
      '.text-_b32rpx_B { font-size: 32rpx; }',
      '.divide-x-8 {',
      '  border-left-width: calc(8rpx * (1 - var(--tw-divide-x-reverse)));',
      '}',
    ].join('\n'))
  })

  it('removes optional Tailwind CSS v4 root variable snapshot noise', () => {
    expect(normalizeCssSnapshot([
      ':host, page, .tw-root, wx-root-portal-content {',
      '  --tw-rotate-x: initial;',
      '  --tw-gradient-position: initial;',
      '  --font-sans: ui-sans-serif;',
      '  --spacing: 8rpx;',
      '}',
      '::before, ::after {',
      '  --tw-content: "";',
      '}',
      '.bg-gradient-to-r {',
      '  --tw-gradient-position: to right in oklab;',
      '}',
    ].join('\n'), {
      normalizeTailwindV4RootVariableNoise: true,
    })).toBe([
      ':host, page, .tw-root, wx-root-portal-content {',
      '  --font-sans: ui-sans-serif;',
      '  --spacing: 8rpx;',
      '}',
      '.bg-gradient-to-r {',
      '  --tw-gradient-position: to right in oklab;',
      '}',
    ].join('\n'))
  })

  it('normalizes Tailwind CSS v4 default token output differences', () => {
    expect(normalizeCssSnapshot([
      ':host {',
      '  --spacing: 8rpx;',
      '  --color-gray-200: rgb(229, 231, 235);',
      '  --color-gray-400: rgb(153, 161, 175);',
      '  --blur: 8rpx;',
      '  --drop-shadow: 0 1rpx 2rpx rgba(0, 0, 0, 0.1);',
      '  --radius: 8rpx;',
      '  --backdrop-blur: 8rpx;',
      '}',
      '.rounded {',
      '  border-radius: var(--radius);',
      '}',
      '.blur {',
      '  --tw-blur: blur(var(--blur));',
      '}',
      '.blur-emitted {',
      '  --tw-blur: blur(8rpx);',
      '}',
      '.shadow-sm {',
      '  --tw-shadow: 0 1px 2px 0 var(--tw-shadow-color, rgba(0, 0, 0, 0.05));',
      '}',
      '.shadow-sm-rpx {',
      '  --tw-shadow: 0 1rpx 3rpx 0 rgba(0, 0, 0, 0.10196), 0 1rpx 2rpx -1rpx rgba(0, 0, 0, 0.10196);',
      '}',
      '.drop-shadow {',
      '  --tw-drop-shadow: drop-shadow(var(--drop-shadow));',
      '}',
      '.drop-shadow-emitted {',
      '  --tw-drop-shadow: drop-shadow(0 1rpx 2rpx rgba(0, 0, 0, 0.1)) drop-shadow(0 1rpx 1rpx rgba(0, 0, 0, 0.06));',
      '}',
      '.backdrop-blur {',
      '  --tw-backdrop-blur: blur(var(--backdrop-blur));',
      '}',
      '.backdrop-blur-emitted {',
      '  --tw-backdrop-blur: blur(8rpx);',
      '}',
      '.outline {',
      '  outline-width: 3rpx;',
      '}',
      '.outline-px {',
      '  outline-width: 1rpx;',
      '}',
      '.ring {',
      '  --tw-ring-shadow: var(--tw-ring-inset,) 0 0 0 calc(3rpx + var(--tw-ring-offset-width)) var(--tw-ring-color, var(--color-blue-500, #3b82f6));',
      '}',
      '.ring-px {',
      '  --tw-ring-shadow: var(--tw-ring-inset,) 0 0 0 calc(3px + var(--tw-ring-offset-width)) var(--tw-ring-color, var(--color-blue-500, #3b82f6));',
      '}',
    ].join('\n'))).toBe([
      ':host {',
      '  --spacing: 8rpx;',
      '}',
      '.rounded {',
      '  border-radius: 8rpx;',
      '}',
      '.blur {',
      '  --tw-blur: blur(8px);',
      '}',
      '.blur-emitted {',
      '  --tw-blur: blur(8px);',
      '}',
      '.shadow-sm {',
      '  --tw-shadow: 0 1px 3px 0 var(--tw-shadow-color, rgba(0, 0, 0, 0.1)), 0 1px 2px -1px var(--tw-shadow-color, rgba(0, 0, 0, 0.1));',
      '}',
      '.shadow-sm-rpx {',
      '  --tw-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1);',
      '}',
      '.drop-shadow {',
      '  --tw-drop-shadow: drop-shadow(0 1px 2px rgba(0, 0, 0, 0.1)) drop-shadow(0 1px 1px rgba(0, 0, 0, 0.06));',
      '}',
      '.drop-shadow-emitted {',
      '  --tw-drop-shadow: drop-shadow(0 1px 2px rgba(0, 0, 0, 0.1)) drop-shadow(0 1px 1px rgba(0, 0, 0, 0.06));',
      '}',
      '.backdrop-blur {',
      '  --tw-backdrop-blur: blur(8px);',
      '}',
      '.backdrop-blur-emitted {',
      '  --tw-backdrop-blur: blur(8px);',
      '}',
      '.outline {',
      '  outline-width: 1px;',
      '}',
      '.outline-px {',
      '  outline-width: 1px;',
      '}',
      '.ring {',
      '  --tw-ring-shadow: var(--tw-ring-inset,) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color, currentcolor);',
      '}',
      '.ring-px {',
      '  --tw-ring-shadow: var(--tw-ring-inset,) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color, currentcolor);',
      '}',
    ].join('\n'))
  })

  it('normalizes Tailwind CSS v4 color output differences', () => {
    expect(normalizeCssSnapshot([
      ':host, page, .tw-root, wx-root-portal-content {',
      '  --font-mono: ui-monospace;',
      '  --color-white: #fff;',
      '  --color-gray-100: #f3f4f6;',
      '  --color-blue-500: #3b82f6;',
      '  --color-red-500: #ef4444;',
      '  --color-brand: #155dfc;',
      '  --spacing: 8rpx;',
      '}',
      '.shadow {',
      '  --tw-shadow-color: var(--color-blue-500);',
      '}',
      '.ring {',
      '  --tw-ring-color: var(--color-cyan-500, #06b6d4);',
      '}',
      '.bg-blue-500_f30 {',
      '  background-color: rgba(59, 130, 246, 0.3);',
      '}',
      '.text-red-500 {',
      '  color: var(--color-red-500);',
      '}',
    ].join('\n'))).toBe([
      ':host, page, .tw-root, wx-root-portal-content {',
      '  --font-mono: ui-monospace;',
      '  --color-red-500: rgb(251, 44, 54);',
      '  --color-brand: #155dfc;',
      '  --spacing: 8rpx;',
      '}',
      '.shadow {',
      '  --tw-shadow-color: var(--color-blue-500);',
      '}',
      '.ring {',
      '  --tw-ring-color: var(--color-cyan-500, #06b6d4);',
      '}',
      '.bg-blue-500_f30 {',
      '  background-color: rgba(50, 128, 255, 0.3);',
      '}',
      '.text-red-500 {',
      '  color: var(--color-red-500);',
      '}',
    ].join('\n'))
  })

  it('normalizes webpack app root base split noise', () => {
    expect(normalizeCssSnapshot([
      '@font-face {',
      '  font-family: JDZH-Regular;',
      '  src: url(data:font/ttf;base64,regular) format("truetype");',
      '}',
      '@font-face {',
      '  font-family: "JDZH-Bold";',
      '  src: url(data:font/ttf;base64,bold) format("truetype");',
      '}',
      ':host, page, .tw-root, wx-root-portal-content {',
      '  --spacing: 8rpx;',
      '}',
      'view, text, :after, :before {',
      '  --tw-gradient-position: initial;',
      '  box-sizing: border-box;',
      '  border-width: 0;',
      '}',
      'view, text, :after, :before {',
      '  border: 0 solid;',
      '  box-sizing: border-box;',
      '  margin: 0;',
      '  padding: 0;',
      '}',
      '@-webkit-keyframes float-pop {',
      '  from { top: 0; }',
      '}',
      '@keyframes jump {',
      '  from { transform: none; }',
      '}',
      '@-webkit-keyframes nutFadeIn {',
      '  from { opacity: 0; }',
      '}',
      '@keyframes nutZoomOut {',
      '  to { opacity: 0; }',
      '}',
      '@-webkit-keyframes nutJump {',
      '  to { transform: translateY(-20rpx); }',
      '}',
      '@keyframes nutBounce {',
      '  50% { transform: scale(1.2); }',
      '}',
    ].join('\n'), {
      normalizeWebpackAppSplitNoise: true,
    })).toBe([
      '@font-face {',
      '  font-family: JDZH-Regular;',
      '  src: url(data:font/ttf;base64,<stable>) format("truetype");',
      '}',
      '@font-face {',
      '  font-family: "JDZH-Bold";',
      '  src: url(data:font/ttf;base64,<stable>) format("truetype");',
      '}',
      ':host, page, .tw-root, wx-root-portal-content {',
      '  --spacing: 8rpx;',
      '  --tw-gradient-position: initial;',
      '}',
    ].join('\n'))
  })

  it('normalizes webpack app root rules with duplicated selectors', () => {
    expect(normalizeCssSnapshot([
      '@font-face {',
      '  font-family: JDZH-Regular;',
      '}',
      ':host, page, .tw-root, wx-root-portal-content {',
      '  --spacing: 8rpx;',
      '}',
      'page:not(#\\#), .tw-root:not(#\\#), wx-root-portal-content:not(#\\#), page:not(#\\#), :host:not(#\\#) {',
      '  --nutui-brand-1: #ffebf1;',
      '}',
      '.static {',
      '  position: static;',
      '}',
      '.h-14 {',
      '  height: calc(var(--spacing) * 14);',
      '}',
    ].join('\n'), {
      normalizeWebpackAppSplitNoise: true,
    })).toBe([
      '@font-face {',
      '  font-family: JDZH-Regular;',
      '}',
      ':host, page, .tw-root, wx-root-portal-content {',
      '  --spacing: 8rpx;',
      '  --nutui-brand-1: #ffebf1;',
      '}',
      '.static {',
      '  position: static;',
      '}',
      '.h-14 {',
      '  height: calc(var(--spacing) * 14);',
      '}',
    ].join('\n'))
  })
})
