export { createAuthorSelectorMatcher } from './author-selector'
export { type DynamicColorMixAlphaProtection, type DynamicColorMixAlphaProtectionOptions, type ModernColorValueNormalization, normalizeModernColorValue, protectDynamicColorMixAlpha, protectDynamicVarFallbacks } from './color-mix'
export { collectDedupedPostTransformCompatCss, collectGeneratedSelectors, inheritLegacyUnitConvertedDeclarations, normalizeCompatSelectors, removeGeneratedSelectorCompatCss, removeTailwindApplyRules } from './legacy-css'
export { normalizeLegacyCompatCssSource, removeMiniProgramContainerCompatCss } from './legacy-css/source-cleanup'
export { transformLynxCssCompat } from './lynx-css'
export { consumeCascadeLayers, finalizeMiniProgramCss, type FinalizeMiniProgramCssOptions, finalizeMiniProgramCssRoot, finalizeMiniProgramCssStructure, hasEmptyCssBlockCandidate, hasMiniProgramCssSpecificityPlaceholders, hoistTailwindPreflightBase, normalizeMiniProgramGeneratedCssForPostcss, pruneMiniProgramGeneratedCss, removeEmptyAtRules, removeEmptyRules, removeUnsupportedAtSupports, removeUnsupportedCascadeLayers, removeUnsupportedMiniProgramAtRules, removeUnusedMiniProgramContentInit, repairTrailingUnclosedTailwindSourceMedia, stripMiniProgramCssSpecificityPlaceholders, unwrapUnsupportedCascadeLayers } from './mini-program-css'
export { normalizeMiniProgramGeneratorCssSource, normalizeMiniProgramImportShell, removeMiniProgramOutputImports, removeSelfMiniProgramOutputImports } from './mini-program-css/output-import-shell'
export { normalizeMiniProgramPrefixedDeclaration, removeUnsupportedMiniProgramPrefixedAtRule } from './mini-program-prefixes'
export { hasNonCommentCss, isCssImportOnly, removeCommentOnlyAtRules, restoreProcessedCssImports } from './processed-css/cleanup'
export { composeProcessedCssSources } from './processed-css/composition'
export { removeTailwindEntryDirectivesFromCss } from './processed-css/entry-directives'
export { collectImportedCssFiles, isStyleImportRequest, normalizeInjectableCssWithImports } from './processed-css/imports'
export { removeCssCoveredByRootStyleSources, removeScopedTailwindPreflightCss } from './scoped-css/cleanup'
export { collectRootScopedComparableCssCoverage, type ComparableCssCoverage, isRuleCoveredByRootCss } from './scoped-css/coverage'
export { removeCssRulesCoveredBySources } from './scoped-css/covered-rules'
export { hasScopedMiniProgramTailwindContentInitRule, hasScopedUniAppWebTailwindPreflightRule, hasUnscopedMiniProgramTailwindPreflightRule, hasVueScopedAttr, isLikelyTailwindGlobalRule, isLikelyTailwindLayerOrderAtRule, isLikelyTailwindPropertyAtRule, isScopedMiniProgramTailwindContentInitRule, isScopedUniAppWebTailwindPreflightRule, isScopedUniversalTailwindPreflightRule, isUnscopedMiniProgramTailwindPreflightRule, normalizeCssSignatureValue } from './scoped-css/predicates'
export { injectTailwindDirectives, type TailwindDirectiveInjectionOptions } from './tailwind-directive-injection'
export { convertTailwindcssRpxDeclarationsToRem, convertTailwindcssRpxDeclarationToRem, convertTailwindcssRpxValueToRem, normalizeTailwindcssRpxDeclaration, normalizeTailwindcssRpxDeclarations, normalizeTailwindcssWebRpxDeclarations, type TailwindcssRpxToRemOptions } from './tailwindcss-rpx'
export { normalizeTailwindcssV4InfinityCalcCss } from './tailwindcss-v4'
export { compileTailwindAuthorFunctions, createTailwindAuthorFunctionProbe } from './tailwindcss-v4/author-functions'
export { normalizeTailwindV4GeneratedUrlValues, transformTailwindV4CssToWeapp, transformTailwindV4GeneratedCss, transformTailwindV4WebRpxCss } from './tailwindcss-v4/generated-output'
export { normalizeTailwindcssV4InfinityRadiusCss } from './tailwindcss-v4/infinity-radius'
export { rewriteTailwindPackageImportStatements } from './tailwindcss-v4/package-import-statements'
export { includesTailwindV4PreflightDirective, isTailwindV4CssImportParam, isTailwindV4PreflightImportParam } from './tailwindcss-v4/preflight-imports'
export { normalizeRpxLengthCandidates, restoreRpxLengthCandidates, restoreRpxLengthCssSelectors } from './tailwindcss-v4/rpx-candidates'
export { insertTailwindThemeCss } from './tailwindcss-v4/theme-injection'
export { normalizeTailwindV4RuntimeCss, removeTailwindV4PreflightImports, removeUnsupportedThemeVendorKeyframes } from './tailwindcss-v4/theme-source'

export { filterTailwindV4ApplyOnlyGeneratedCss, normalizeEmptyTailwindCustomVariants } from './tailwindcss-v4/user-css/apply-only'
export { createTailwindV4SourceReferenceSource, hasTailwindApplyContextDirective } from './tailwindcss-v4/user-css/apply-reference'
export { removeTailwindApplyAtRules, removeTailwindSourceMediaBlocks, terminateTailwindSourceAtRulesBeforeNextDirective } from './tailwindcss-v4/user-css/at-rules'
export { collectRawSourceClassSelectors, normalizeCssClassSelector } from './tailwindcss-v4/user-css/class-selectors'
export { hasLocalCssImport, hasTailwindApplyDirective, hasTailwindNonRootGenerationDirectives, hasTailwindRootDirectives, hasTailwindRootImportDirectives, hasTailwindSourceDirectives, normalizeTailwindConfigDirectives, normalizeTailwindSourceDirectives, normalizeTailwindSourceForGenerator, parseImportRequest, removeTailwindSourceDirectives, resolveCssEntrySource } from './tailwindcss-v4/user-css/directives'
export { extractConfigRequestFromSource, extractTailwindDirectiveLines, extractTailwindSourceForPostcssFallback } from './tailwindcss-v4/user-css/directives/fallback'
export { composeFrameworkProcessedCss } from './tailwindcss-v4/user-css/framework-composition'
export { normalizeFrameworkProcessedUserCss } from './tailwindcss-v4/user-css/framework-source'
export { createGeneratedThemeDeclarationResolver, type GeneratedThemeDeclarationResolver, removeBalancedAtRuleBlock, removeTailwindV4GeneratedUserCssArtifacts, removeTailwindV4GeneratorAtRulesFallback, TAILWIND_V4_GENERATOR_AT_RULES } from './tailwindcss-v4/user-css/generated-cleanup'
export { isCssAlreadyRepresentedByMarkers } from './tailwindcss-v4/user-css/identity'
export { createCssAppend, GENERATOR_PLACEHOLDER_MARKER_GLOBAL_RE, GENERATOR_PLACEHOLDER_MARKER_RE, hasTailwindGeneratedCss, hasTailwindGeneratedCssMarkers, removeDuplicatedViteMarkers, removeTailwindGeneratedCssByBanner, splitGeneratorPlaceholderCssBySourceOrder, splitTailwindGeneratedCssByBanner, splitTailwindV4GeneratedCss, splitTailwindV4GeneratedCssBySourceOrder, stripGeneratorPlaceholderMarkers, stripTailwindBanner, stripTailwindBannerComments, stripTailwindBanners, TAILWIND_BANNER_GLOBAL_RE, TAILWIND_BANNER_PREFIX_RE, TAILWIND_BANNER_RE, TAILWIND_GENERATED_CSS_MARKER_RE, TAILWIND_V4_BANNER_RE, VITE_MARKER_RE } from './tailwindcss-v4/user-css/markers'

export { deduplicateGeneratedCssRules } from './tailwindcss-v4/user-css/rule-deduplication'
export { preferScopedGeneratedCssRules, preferScopedGeneratedCssRulesRoot } from './tailwindcss-v4/user-css/scoped-rules'

export { collectBareSelectorUserCss, isCommentOnlyCss, removeMiniProgramHoverSelectors, removeMiniProgramInteractiveSelectors, type RemoveMiniProgramInteractiveSelectorsOptions, removeProcessedMiniProgramUnsupportedCss, removeTailwindV4GeneratorAtRules, stripTailwindSourceMediaFragments, stripUnmatchedTailwindSourceMediaCloseFragments, unwrapMiniProgramCascadeLayers } from './tailwindcss-v4/user-css/source-fragments'
export { transformGeneratorUserCss } from './tailwindcss-v4/user-css/transform'
export { extractMarkedUserLayerComponentsCss, mergeMarkedUserLayerComponentsCss, reorderMarkedUserLayerComponentsCss, wrapUserLayerComponentsCss } from './tailwindcss-v4/user-css/user-layer-order'
export { analyzeApplyOnlySource, collectApplyOnlySourceSelectors, extractGeneratedCssForUserLayerSelectors, hasOnlyApplyBackedSourceRules, hasUserCssLayerBlocks, isEmptyCustomVariantBlock, normalizeGeneratedSelector, removeCssComments, splitUserCssLayerBlocks } from './tailwindcss-v4/user-css/user-layers'

export { normalizeUniAppXImportantApplyForSass, restoreUniAppXImportantApplyMarker, UNI_APP_X_IMPORTANT_APPLY_MARKER } from './uni-app-x'
export { isTailwindRuntimePropertyRule, retainUniAppXAuthorApplyCss } from './uni-app-x-author-apply'
export { createUniAppXBorderPreflight, hoistUniAppXBorderPreflight, UNI_APP_X_BORDER_PREFLIGHT_CLASS } from './uni-app-x-border'
export { collectCssApplyUtilities, type CssClassStyleValue, cssToClassStyleValue, expandCssApplySourcesToStyleValue } from './uni-app-x-style-value'
export { collectCssReferenceDirectives, createUniAppXHarmonyApplyGeneratorSource } from './uni-app-x/apply-source'
export { createUniAppXHarmonyApplyCssExpander } from './uni-app-x/harmony-apply'
export { rewriteUniAppXStyleReferences } from './uni-app-x/reference-paths'
export { type NormalizedWebCssCompatOptions, normalizeWebCssCompatOptions, transformWebCssCompat, transformWebCssSafeSelectors } from './web-css'
export { collectWebpackBareSelectorUserCss } from './webpack-css/bare-selectors'
export { isOnlyWebpackTailwindGeneratedPreflightCss, parseWebpackCssLayerNames, removeWebpackTailwindGeneratedAssetCss, stripTrailingLineWhitespace } from './webpack-css/generated-cleanup'

export { collectGeneratedCssClassCandidates, collectWebpackAssetUserCssMarkers, collectWebpackCssRuleIdentityMarkers, hasAdditionalWebpackAssetUserCssMarkers, unescapeCssIdentifier } from './webpack-css/identity'
export { dedupeMiniProgramPreflightSelectorRules, ensureWebpackMiniProgramTwContentInit, hasMiniProgramPreflightSelector, removeMiniProgramPreflightSelectorRule, removeTailwindV4StandaloneHostPreflightRule } from './webpack-css/preflight'
export { hasWebpackTailwindSourceDirectives, isWebpackCssSourceRepresentedInAsset, isWebpackTailwindImportRequest, normalizeWebpackUserCssFallbackSource, removeWebpackGeneratorNonTailwindImports, removeWebpackUserCssFallbackImports } from './webpack-css/user-source'
