/* eslint-disable no-template-curly-in-string */
// https://github.com/cnpm/binary-mirror-config/blob/master/package.json

export const chinaMirrorsEnvs = {
  COREPACK_NPM_REGISTRY: 'https://registry.npmmirror.com',
  EDGEDRIVER_CDNURL: 'https://npmmirror.com/mirrors/edgedriver',
  NODEJS_ORG_MIRROR: 'https://cdn.npmmirror.com/binaries/node',
  NVM_NODEJS_ORG_MIRROR: 'https://cdn.npmmirror.com/binaries/node',
  PHANTOMJS_CDNURL: 'https://cdn.npmmirror.com/binaries/phantomjs',
  CHROMEDRIVER_CDNURL: 'https://cdn.npmmirror.com/binaries/chromedriver',
  OPERADRIVER_CDNURL: 'https://cdn.npmmirror.com/binaries/operadriver',
  CYPRESS_DOWNLOAD_PATH_TEMPLATE: 'https://cdn.npmmirror.com/binaries/cypress/${version}/${platform}-${arch}/cypress.zip',
  ELECTRON_MIRROR: 'https://cdn.npmmirror.com/binaries/electron/',
  ELECTRON_BUILDER_BINARIES_MIRROR: 'https://cdn.npmmirror.com/binaries/electron-builder-binaries/',
  SASS_BINARY_SITE: 'https://cdn.npmmirror.com/binaries/node-sass',
  SWC_BINARY_SITE: 'https://cdn.npmmirror.com/binaries/node-swc',
  NWJS_URLBASE: 'https://cdn.npmmirror.com/binaries/nwjs/v',
  PUPPETEER_DOWNLOAD_HOST: 'https://cdn.npmmirror.com/binaries/chrome-for-testing',
  PUPPETEER_DOWNLOAD_BASE_URL: 'https://cdn.npmmirror.com/binaries/chrome-for-testing',
  PLAYWRIGHT_DOWNLOAD_HOST: 'https://cdn.npmmirror.com/binaries/playwright',
  SENTRYCLI_CDNURL: 'https://cdn.npmmirror.com/binaries/sentry-cli',
  SAUCECTL_INSTALL_BINARY_MIRROR: 'https://cdn.npmmirror.com/binaries/saucectl',
  RE2_DOWNLOAD_MIRROR: 'https://cdn.npmmirror.com/binaries/node-re2',
  RE2_DOWNLOAD_SKIP_PATH: 'true',
  PRISMA_ENGINES_MIRROR: 'https://cdn.npmmirror.com/binaries/prisma',
  npm_config_better_sqlite3_binary_host: 'https://cdn.npmmirror.com/binaries/better-sqlite3',
  npm_config_keytar_binary_host: 'https://cdn.npmmirror.com/binaries/keytar',
  npm_config_sharp_binary_host: 'https://cdn.npmmirror.com/binaries/sharp',
  npm_config_sharp_libvips_binary_host: 'https://cdn.npmmirror.com/binaries/sharp-libvips',
  npm_config_robotjs_binary_host: 'https://cdn.npmmirror.com/binaries/robotjs',
}
