import { disposeTheme, refreshSystemTheme } from '@/stores/theme.uts'

// #ifdef APP-ANDROID || APP-HARMONY
let firstBackTime = 0
// #endif

onLaunch(() => {
	console.log('App Launch')
})

onAppShow(() => {
	refreshSystemTheme()
})

onAppHide(() => {
	console.log('App Hide')
})

// #ifdef APP-ANDROID || APP-HARMONY
onLastPageBackPress(() => {
	console.log('App LastPageBackPress')
	if (firstBackTime == 0) {
		uni.showToast({
			title: '再按一次退出应用',
			position: 'bottom'
		})
		firstBackTime = Date.now()
		setTimeout(() => {
			firstBackTime = 0
		}, 2000)
	} else if (Date.now() - firstBackTime < 2000) {
		firstBackTime = Date.now()
		uni.exit()
	}
})

onExit(() => {
	disposeTheme()
})
// #endif
