const TAILWIND_V4_LEGACY_DEFAULTS_CSS = [
  '@theme default {',
  '  --default-ring-width: 3px;',
  '  --default-ring-color: var(--color-blue-500, #3b82f6);',
  '  --default-outline-width: 3px;',
  '',
  '  --shadow-xs: 0 1px rgb(0 0 0 / 0.05);',
  '  --shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);',
  '  --shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);',
  '  --drop-shadow-xs: 0 1px 1px rgb(0 0 0 / 0.05);',
  '  --drop-shadow-sm: 0 1px 2px rgb(0 0 0 / 0.15);',
  '  --drop-shadow: 0 1px 2px rgb(0 0 0 / 0.1), 0 1px 1px rgb(0 0 0 / 0.06);',
  '',
  '  --blur-xs: 4px;',
  '  --blur-sm: 4px;',
  '  --blur: 8px;',
  '  --backdrop-blur-xs: 4px;',
  '  --backdrop-blur-sm: 4px;',
  '  --backdrop-blur: 8px;',
  '',
  '  --radius-xs: 0.125rem;',
  '  --radius-sm: 0.125rem;',
  '  --radius: 0.25rem;',
  '}',
  '',
  '@layer base {',
  '  *,',
  '  ::after,',
  '  ::before,',
  '  ::backdrop,',
  '  ::file-selector-button {',
  '    border-color: var(--color-gray-200, currentcolor);',
  '  }',
  '}',
].join('\n')

export function appendTailwindV4LegacyDefaultsCss(css: string) {
  return `${css}\n${TAILWIND_V4_LEGACY_DEFAULTS_CSS}`
}
