import type { Locale, SceneId } from '../config'

const zh = {
  chapter: { intro: '跨端样式', craft: '原子化开发', pipeline: '目标端产物', platforms: '支持范围', ecosystem: '开发生态', setup: '开始使用', tools: '更多工具', cta: '开始构建' } satisfies Record<SceneId, string>,
  heading: { intro: ['Tailwind，', '不止 Web。'], craft: ['改 class。', '看见变化。'], pipeline: ['同一套输入。', '按目标端输出。'], platforms: ['熟悉的写法。', '更多的屏幕。'], ecosystem: ['你的框架。', '你的构建工具。'], setup: ['从这里，', '开始构建。'], tools: ['从样式构建，', '到组件变体。'], cta: ['选你的框架。', '开始构建。'] } satisfies Record<SceneId, string[]>,
  hookTag: 'Tailwind CSS 4 · 跨端工具链',
  hookTargets: 'Web / 小程序 / 原生跨端生态',
  craftLabels: ['间距', '圆角', '色彩'],
  design: '界面设计示意',
  pipelineSteps: ['生成样式', '转译类名', '平台适配'],
  pipelineDetails: ['Tailwind CSS 4', '精确命中已生成类名', '对应平台集成'],
  outputLabels: ['Web CSS', '小程序样式', '原生样式产物'],
  targetLabels: ['Web / H5', '小程序', 'App WebView', 'uni-app x', 'React Native / Expo', 'Lynx'],
  targetDetails: ['浏览器 CSS', '微信 / 支付宝 / 抖音 / QQ', 'uni-app / Taro', 'Android / iOS / HarmonyOS', 'Metro / Babel / 样式清单', 'ReactLynx / Rspeedy'],
  targetGroup: ['Web 与小程序', '原生跨端生态'],
  supportNote: '样式能力以目标运行时为准',
  frameworkLabel: '框架集成',
  builderLabel: '构建入口',
  setupSteps: ['安装依赖', '引入 CSS', '注册插件'],
  setupTarget: 'Vite / Web 接入示例',
  setupHint: '其他目标端，选择对应接入指南',
  setupMobile: ['安装依赖', '选择框架接入', '引入样式入口'],
  toolsNames: ['独立 CSS 构建', '类名与组件变体'],
  toolsNotes: ['CLI / watch / 小程序 CSS-only', 'merge / variants / cva'],
  variants: ['主要按钮', '次要按钮', '小尺寸'],
  ctaLabel: '文档 · 模板 · 示例',
  ctaScan: '扫码，开始构建',
  interface: { daily: '每日灵感', title: '灵感，从这里开始', subtitle: '让想法拥有自己的形状。', card: '探索新的可能', tabs: ['灵感收藏', '设计系统', '我的空间'], color: '给创作，一点新颜色', palette: '属于你的设计语言', create: '构建。探索。创造。', art: '让想法成形', side: ['创作空间', '灵感收藏', '设计系统', '我的项目'] },
}
const en: typeof zh = {
  chapter: { intro: 'Beyond the web', craft: 'Utility-first styling', pipeline: 'Targeted output', platforms: 'Platform support', ecosystem: 'Your ecosystem', setup: 'Quick start', tools: 'More tools', cta: 'Start building' },
  heading: { intro: ['Tailwind.', 'Beyond the web.'], craft: ['Change classes.', 'Shape the UI.'], pipeline: ['One input.', 'Targeted output.'], platforms: ['Familiar classes.', 'More screens.'], ecosystem: ['Your framework.', 'Your build tools.'], setup: ['Your next screen', 'starts here.'], tools: ['Build styles.', 'Compose variants.'], cta: ['Pick your framework.', 'Start building.'] },
  hookTag: 'Tailwind CSS 4 · Cross-platform tooling',
  hookTargets: 'Web / Mini programs / Native ecosystems',
  craftLabels: ['Spacing', 'Corners', 'Color'],
  design: 'UI illustration',
  pipelineSteps: ['Generate', 'Transform', 'Adapt'],
  pipelineDetails: ['Tailwind CSS 4', 'Generated classes only', 'Platform integrations'],
  outputLabels: ['Web CSS', 'Mini-program styles', 'Native style output'],
  targetLabels: ['Web / H5', 'Mini programs', 'App WebView', 'uni-app x', 'React Native / Expo', 'Lynx'],
  targetDetails: ['Browser CSS', 'WeChat / Alipay / Douyin / QQ', 'uni-app / Taro', 'Android / iOS / HarmonyOS', 'Metro / Babel / style manifest', 'ReactLynx / Rspeedy'],
  targetGroup: ['Web & mini programs', 'Native ecosystems'],
  supportNote: 'Style support varies by runtime',
  frameworkLabel: 'Framework integrations',
  builderLabel: 'Build integrations',
  setupSteps: ['Install packages', 'Import CSS', 'Add the plugin'],
  setupTarget: 'Vite / Web example',
  setupHint: 'Choose the integration guide for your target',
  setupMobile: ['Install packages', 'Choose your integration', 'Import your styles'],
  toolsNames: ['Standalone CSS builds', 'Classes & variants'],
  toolsNotes: ['CLI / watch / mini-program CSS-only', 'merge / variants / cva'],
  variants: ['Primary', 'Secondary', 'Small'],
  ctaLabel: 'Docs · Templates · Examples',
  ctaScan: 'Scan to start building',
  interface: { daily: 'DAILY INSPIRATION', title: 'Make room for ideas', subtitle: 'Give every idea its own shape.', card: 'Explore what comes next', tabs: ['Saved', 'Design system', 'My space'], color: 'A little color. A new idea.', palette: 'Your design language', create: 'Build. Explore. Create.', art: 'MAKE IT YOURS', side: ['Workspace', 'Saved ideas', 'Design system', 'My projects'] },
}
export const copy: Record<Locale, typeof zh> = { zh, en }
export const setupCode = [
  ['pnpm add -D tailwindcss weapp-tailwindcss'],
  ['@import "tailwindcss";', '@source "./**/*.{html,js,ts,jsx,tsx,vue}";', '', '// main.ts', 'import "./app.css";'],
  ['import { defineConfig } from "vite";', 'import { WeappTailwindcssWeb }', '  from "weapp-tailwindcss/vite/web";', '', 'export default defineConfig({', '  plugins: [WeappTailwindcssWeb()],', '});'],
]
