export const LEGACY_SOURCE_IGNORED_PATTERNS = [
  '**/.git/**',
  '**/.hg/**',
  '**/.jj/**',
  '**/.next/**',
  '**/.parcel-cache/**',
  '**/.pnpm-store/**',
  '**/.svelte-kit/**',
  '**/.svn/**',
  '**/.turbo/**',
  '**/.venv/**',
  '**/.vercel/**',
  '**/.yarn/**',
  '**/__pycache__/**',
  '**/node_modules/**',
  '**/venv/**',
  '**/*.less',
  '**/*.lock',
  '**/*.sass',
  '**/*.scss',
  '**/*.styl',
  '**/*.log',
  '**/tailwind.config.js',
  '**/tailwind.config.cjs',
  '**/tailwind.config.mjs',
  '**/tailwind.config.ts',
  '**/tailwind.config.cts',
  '**/tailwind.config.mts',
  '**/tailwind.config.*.js',
  '**/tailwind.config.*.cjs',
  '**/tailwind.config.*.mjs',
  '**/tailwind.config.*.ts',
  '**/tailwind.config.*.cts',
  '**/tailwind.config.*.mts',
  '**/package-lock.json',
  '**/pnpm-lock.yaml',
  '**/bun.lockb',
  '**/.gitignore',
  '**/.env',
  '**/.env.*',
]

const TAILWIND_V4_IGNORED_CONTENT_DIRS = [
  '.git',
  '.hg',
  '.jj',
  '.next',
  '.parcel-cache',
  '.pnpm-store',
  '.svelte-kit',
  '.svn',
  '.turbo',
  '.venv',
  '.vercel',
  '.yarn',
  '__pycache__',
  'node_modules',
  'venv',
]
const TAILWIND_V4_IGNORED_EXTENSIONS = [
  'css',
  'less',
  'postcss',
  'pcss',
  'lock',
  'sass',
  'scss',
  'styl',
  'stylus',
  'log',
  'wxss',
  'acss',
  'jxss',
  'ttss',
  'qss',
  'tyss',
]
const TAILWIND_V4_IGNORED_FILES = [
  'package-lock.json',
  'pnpm-lock.yaml',
  'bun.lockb',
  '.gitignore',
  '.env',
  '.env.*',
]

export const CANDIDATE_SOURCE_IGNORED_PATTERNS = [
  ...TAILWIND_V4_IGNORED_CONTENT_DIRS.map(directory => `**/${directory}/**`),
  ...TAILWIND_V4_IGNORED_EXTENSIONS.map(extension => `**/*.${extension}`),
  ...TAILWIND_V4_IGNORED_FILES.map(file => `**/${file}`),
]
