const filters = [
  'E2E_PROJECT_FILTER',
  'E2E_TEMPLATE_CASE',
  'E2E_TEMPLATE_HMR_CASE',
  'E2E_TEMPLATE_IDE_CASE',
  'E2E_CANONICAL_TEMPLATE_CASE',
  'E2E_STARTER_CASE',
  'E2E_DEV_STARTUP_CASE',
  'E2E_WEB_VITE_HMR_CASE',
  'E2E_HBUILDERX_CASE',
  'E2E_HBUILDERX_CASE_GROUP',
  'E2E_HBUILDERX_APP_PLATFORM',
  'E2E_HBUILDERX_MP_PLATFORM',
  'E2E_HOT_UPDATE_CASE_NAME',
  'E2E_HOT_UPDATE_CI',
  'HOT_UPDATE_CI_CASES',
  'E2E_IDE_REQUIRE_LIVE_PAGE_VISIBILITY',
  'E2E_WATCH_CASE',
  'E2E_WATCH_WEB_ONLY',
  'E2E_WATCH_STYLE_ONLY',
  'E2E_WATCH_MAIN_STYLE_ONLY',
  'E2E_WATCH_MINI_PROGRAM_ONLY',
  'E2E_WATCH_MINI_PROGRAM_SCOPE',
  'E2E_WATCH_MAIN_STYLE_SUBPACKAGE_LIMIT',
  'E2E_WATCH_ROUND_PROFILE',
  'DEMO_VISUAL_FILTER',
  'DEMO_VISUAL_STYLE_ISOLATION_VARIANT',
  'RN_ANDROID_BINARY',
  'LYNX_NATIVE_WORK_DIR',
]

const disabled = [
  'RN_UPDATE_BASELINE',
  'E2E_UPDATE_ISSUE_928_BASELINE',
  'E2E_TEMPLATE_SKIP_INSTALL',
  'E2E_TEMPLATE_SKIP_BUILD',
  'E2E_TEMPLATE_HMR_SKIP',
  'E2E_TEMPLATE_HMR_SKIP_INSTALL',
  'E2E_TEMPLATE_IDE_SKIP_INSTALL',
  'E2E_TEMPLATE_IDE_SKIP_BUILD',
  'E2E_CANONICAL_TEMPLATE_SKIP_INSTALL',
  'E2E_CANONICAL_TEMPLATE_SKIP_BUILD',
  'E2E_CANONICAL_TEMPLATE_USE_LOCAL',
  'E2E_STARTER_SKIP_BUILD',
  'E2E_SKIP_BUILD',
  'E2E_SKIP_HBUILDERX',
  'E2E_WATCH_SKIP_BUILD',
  'LYNX_IOS_SKIP_PROJECT_GENERATION',
  'LYNX_IOS_SKIP_POD_INSTALL',
]

/** 扩展验收清除局部调试配置，同时保留工具链、设备和超时配置。 */
export function extendedEnvironment(source: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = {
    ...source,
    CI: '1',
    E2E_IDE_HOT_UPDATE: '1',
    // 完整验收保留首次功能失败；性能异常仍由专门的有界确认流程处理。
    E2E_WATCH_MAX_ATTEMPTS: '1',
  }
  for (const key of filters) {
    delete env[key]
  }
  for (const key of disabled) {
    env[key] = '0'
  }
  return env
}
