packages:
  - "./taro-app"
  - "./taro-vue2-app"
  - "./taro-vue3-app"
  - "./rax-app"
  - "./gulp-app"
  - "./mpx-app"
  - "./native-mina"
  - "./packages"
  - "./uni-app"
  - "./uni-app-vue3-vite"
  - "./uni-app-webpack5"
