source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

target 'LynxCompatibilityHost' do
  use_frameworks! :linkage => :static
  pod 'Lynx', '4.0.1', :subspecs => ['Framework']
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
