name: Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    # https://github.com/webpack/webpack/blob/main/.github/workflows/test.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x] # 16.x,
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm i
      - run: pnpm build
      - run: pnpm test
      # TODO
      # - uses: codecov/codecov-action@v4
      #   with:
      #     directory: coverage
      # files: ./coverage/clover.xml,./coverage-vitest/clover.xml
