import { View } from '@tarojs/components'
import './index.css'

export default function Index() {
  return (
    <View className="min-h-screen bg-slate-50 px-[32rpx] py-[40rpx] text-slate-900">
      <View className="starter-card rounded-[28rpx] border border-sky-200 bg-white p-[32rpx] shadow-sm">
        <View className="text-[40rpx] font-semibold text-sky-700">Taro starter</View>
        <View className="mt-[16rpx] text-[28rpx] leading-relaxed text-slate-600">Tailwind CSS 4 styles are generated by weapp-tailwindcss.</View>
        <View className="mt-[24rpx] flex gap-[16rpx]">
          <View className="h-[48rpx] w-[48rpx] rounded-full bg-emerald-400" />
          <View className="h-[48rpx] w-[96rpx] rounded-[12rpx] bg-violet-400/80" />
        </View>
        <View className="mt-[24rpx] text-[length:24rpx] hover:text-sky-600">starter-marker-taro</View>
      </View>
    </View>
  )
}
